Fix links and NeoForge mentions in README.md
neoforged/NeoForge pull request #1
Opened 2023-07-12 20:07 UTC by Mishura4

(Totally not an excuse to snatch PR #1)

2023-07-12 20:08 UTC, embeddedt commented on docs/README.md
> +NeoForge is a free, open-source modding API all of your favourite mods use!
Third time's the charm?

```suggestion
NeoForge is a free, open-source modding API many of your favourite mods use!
```

2023-07-12 22:22 UTC, Su5eD approved these changes

2023-07-13 00:29 UTC, cpw commented
We'll have to see if this still works after the big update that is currently sitting on my computer, heh.

2023-07-13 07:16 UTC, SizableShrimp requested changes
If we're updating the README, might as well do it right.

> Installing NeoForged
NeoForged is the organization, not the product.
Additionally, this section is bad in general. It links to a dead placeholder curseforge link, which can be confusing to users. And, the information about Latest builds being more unstable is basically bunk nowadays. We should probably delete this section while we figure out what our installation will look like.

> NeoForged is a large project with many collaborators working on it around the clock.
Same issue, it's NeoForge, not NeoForged.

The CLA link and CONTRIBUTING.md doc are both outdated, but those should probably be saved for changing on another day.

2023-07-14 19:22 UTC, hypersmc commented
Please update the download button from the link: https://maven.neoforged.net/releases/net/neoforged/forge/
to: https://maven.neoforged.net/#/releases/net/neoforged/forge/

2023-07-14 21:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/neoforged/NeoForge?pullRequest=1) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: marchermans<br/>:x: Mishura4<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neoforged/NeoForge?pullRequest=1) it.</sub>

2023-07-20 15:56 UTC, cpw commented
Updated to latest tip so this should run all the checks properly and then be ready to merge.

2023-07-20 16:10 UTC, Mishura4 commented
Changed some mentions of NeoForged to NeoForge and vice versa as requested (see https://github.com/neoforged/NeoForge/pull/1#pullrequestreview-1527768434)

2023-07-30 00:52 UTC, DataDalton commented on docs/README.md
> +[CurseForge]: https://curseforge.com/placeholder
Should probably remove this weird placeholder link that's broken and just link directly to Curseforge

2023-07-30 00:57 UTC, DataDalton commented on docs/README.md
Should probably rewrite this original installing NeoForge thing as it doesn't make sense and should say how to install NeoForge without going through Curseforge and linking to the installer on https://neoforged.net/

2023-11-07 16:23 UTC, Technici4n commented
See #232.

2023-11-07 16:23 UTC, closed without merging