Improve legacy tag warning for colored glass migrations
neoforged/NeoForge pull request #1026
Opened 2024-05-27 16:30 UTC by TelepathicGrunt

The legacy colored glass tags were technically migrated to two tags. I adjusted the log warning system to now print both tags so people know it is split into two tags now.

![image](https://github.com/neoforged/NeoForge/assets/40846040/75d3a317-564f-497f-9bdf-a5947440726a)

2024-05-27 19:02 UTC, PaintNinja requested changes
Thanks for implementing my suggestion. This only appears to apply to glass colour variations though - what about other intersection tags, such as e.g. `forge:stained_glass`? Presumably that maps to `c:glass_blocks` + `c:dyed`, right?

2024-05-27 19:08 UTC, TelepathicGrunt commented
missed those tags but added now. Yes it is the intersection of the base block tag + dyed. Colorless is a dedicated tag `c:glass_panes/colorless` and `c:glass_blocks/colorless` because they are not dyed at all nor tinted.

2024-05-27 19:28 UTC, PaintNinja approved these changes

2024-05-28 15:33 UTC, Matyrobbrt approved these changes

2024-05-28 15:34 UTC, merged