[1.20.6] Use stack hash strategy for mutable map in creative tab event
neoforged/NeoForge pull request #1043
Opened 2024-05-31 04:02 UTC by dhyces

Vanilla disallows duplicate elements in creative mode tabs, throwing a pretty unhelpful error:
```
Accidentally adding the same item stack twice [Wooden Sword] to a Creative Mode Tab: Damaged Wooden Swords
```
The current `BuildCreativeModeTabContentsEvent` mutable entries map does allow duplicate elements due to using default object comparison and hashing. This PR changes the hash strategy used to `ItemStackLinkedSet#TYPE_AND_TAG`

Fixes #1040.

2024-05-31 04:07 UTC, TelepathicGrunt commented
Uhhh. Are you _positive_ you are not going to reintroduce this bug where the creative menu enchanted books gets broken or order incorrectly? https://github.com/neoforged/NeoForge/pull/920

2024-05-31 04:15 UTC, dhyces commented
I was not aware of that issue. This does reintroduce that bug. If this does not have a proper solution, then a better error should at least be implemented along with an explanation on the event with why the custom hash strategy cannot be used.

2024-05-31 09:13 UTC, TelepathicGrunt commented
If testing and the enchanted book bug doesn’t happen, then this pr should be alright. Though maybe we should have a junit test added to verify that two of exact same item errors but enchanted books passes. See my Neo startup config PR for an example of a junit test that is also a test mod

2024-05-31 13:42 UTC, TelepathicGrunt commented
ah I see how vanilla bypasses their enchanted books. They deliberately skip checking search only entries lmao. 
<img width="808" alt="image" src="https://github.com/neoforged/NeoForge/assets/40846040/ee47a9b3-b3dd-4d90-a8ca-b1505ab1ede2">

Tested PR and it does break the books tho. While the enchanted books do show up in the search, the normal books are not showing under the Ingredients tabs.
<img width="929" alt="image" src="https://github.com/neoforged/NeoForge/assets/40846040/cd73c81b-3b4d-4daf-bce3-4c9405f63d73">

I think this PR's fix needs to change to allow duplicate itemstacks if the duplicates are search only mode.

2024-05-31 13:44 UTC, TelepathicGrunt requested changes
Ok lets see. I need to leave a proper review asking for changes. PR just needs to solve this bug:
<img width="929" alt="image" src="https://github.com/neoforged/NeoForge/assets/40846040/442713fa-ce3e-49b2-8345-9d2504f89db9">

2024-06-03 21:11 UTC, TelepathicGrunt approved these changes

2024-06-05 00:30 UTC, sciwhiz12 approved these changes

2024-06-05 00:30 UTC, merged