Add more Codecs to NeoForgeExtraCodecs
neoforged/NeoForge pull request #1085
Opened 2024-06-10 15:05 UTC by RaymondBlaze

**New Codecs**:

- Codecs for arrays including primitive arrays. Supports size limits.
- New `aliasFieldOf` Codec supporting alias-specific decoders.
- List version of `singularOrPlural` and `singularOrPluralNotEmpty` Codecs.
- Compressible `setOf` Codec (using implementation similar to EnumSet).
- Codec for enum that doesn't implements `StringRepresentable`.
- Codec for `EnumSet`, compressible by default.

**Changes**:

- Optimized `aliasFieldOf` Codec by flattening the structure (the old implementation wraps `mapWithAlternative` multiple times when aliases are more than 2).
- Made `singularOrPlural` Codec able to decode inputs with neither the singular or the plural key (decode to empty collection in this case) and vice versa, so it's more user friendly.

2024-06-10 15:57 UTC, Technici4n requested changes
I think that this is largely bloat. The helpers that we keep in this class are all used by NeoForge itself, and those that weren't have typically been removed.

2024-06-10 22:36 UTC, XFactHD commented
I'm with Tech on this, most of those are very trivial to just do in the mods that need them.

2024-06-11 01:15 UTC, RaymondBlaze commented
> I think that this is largely bloat. The helpers that we keep in this class are all used by NeoForge itself, and those that weren't have typically been removed.

That's fair, I don't actually believe all of these should be added, but I'm also not sure about what exactly should be added. And hence this PR, I guess I need RFC on this.

From my experience, at least the List version of `singularOrPlural` and `singularOrPluralNotEmpty` Codecs and the enum/EnumSet Codecs are widely used in mods, and could be used in NeoForge.

2024-07-05 01:20 UTC, sciwhiz12 commented
@Technici4n and @XFactHD, what do you think would be useful to keep from this PR? Are all of them bloat or are there ones which we can keep around as more useful to reach for?

(I'd like to be mindful of the balance between a non-bloated API versus providing useful utilities that is better served in the API rather than duplicated across many mods individually.)

@RaymondBlaze, do you intend to update this PR to 1.21?

2024-07-18 18:19 UTC, XFactHD commented
> Are all of them bloat or are there ones which we can keep around as more useful to reach for?

In my opinion, almost all of them are either trivial or too specific to be broadly useful and would be better implemented by the mods that need them. The only one I'd potentially consider broadly useful is the enum one, though without the caching since it's pointless after the extensible enum rework.

2024-07-24 18:50 UTC, TelepathicGrunt commented
Closing as neo team feels this PR doesn't really give enough benefit to warrant moving forward

2024-07-24 18:50 UTC, closed without merging