`SpawnPlacementRegisterEvent` -> `RegisterSpawnPlacementsEvent`
neoforged/NeoForge pull request #1154
Opened 2024-06-20 21:14 UTC by Spinoscythe

Who doesn't like consistency?

2024-06-24 21:57 UTC, Shadows-of-Fire commented on patches/net/minecraft/world/entity/SpawnPlacements.java.patch
> -+    // ******* FORGE START. INTERNAL USE ONLY! ****** //
If you're going to delete the "internal use only" comment, this at least needs an `@ApiStatus.Internal` marker or similar.

2024-07-03 13:23 UTC, sciwhiz12 requested changes, later dismissed

2024-07-03 13:23 UTC, sciwhiz12 commented on patches/net/minecraft/world/entity/SpawnPlacements.java.patch
> ++     * @deprecated modders should use {@link net.neoforged.neoforge.event.entity.RegisterSpawnPlacementsEvent} instead.
Add a "Neo:" and capitalize the word `modders`.
```suggestion
+     * @deprecated Neo: Modders should use {@link net.neoforged.neoforge.event.entity.RegisterSpawnPlacementsEvent} instead.
```

2024-07-06 21:18 UTC, TelepathicGrunt approved these changes

2024-07-07 14:02 UTC, merged