Damage pipeline improvements
neoforged/NeoForge pull request #1177
Opened 2024-06-24 21:00 UTC by Caltinor

This PR contains one bugfix and a few QOL improvements following the rollout of the damage pipeline update.

### Bugfixes
- Fixes incorrect storing and application of reduction modifications

### QOL Features
- Removed `@ApiStatus.Internal` from `DamageContainer`
- Added helper methods to `LivingDamageEvent.Pre` to reduce the bulk of calling `event.getContainer().getXYZ()`

2024-07-02 20:31 UTC, Tslat requested changes
Should we change `new ArrayList()` to `List.of()` in `DamageContainer#modifyReduction` to eliminate the unnecessary object creation?

2024-07-03 22:18 UTC, Tslat approved these changes
Looks good to me
Another set of eyes wouldn't hurt, but I'm good from here

2024-07-05 11:19 UTC, TelepathicGrunt commented on patches/net/minecraft/world/entity/LivingEntity.java.patch
>  +            if (true) return; //Neo: invalidates the loop.  armor damage happens in common hook
Nitpick on comment format
```suggestion
+            if (true) return; //Neo: Invalidates the loop. Armor damage happens in common hook.
```

2024-07-05 11:22 UTC, TelepathicGrunt submitted a review, later dismissed

2024-07-05 12:02 UTC, TelepathicGrunt approved these changes

2024-07-05 13:27 UTC, merged