Fix `ArrowLooseEvent` not firing for bows
neoforged/NeoForge pull request #1189
Opened 2024-06-25 18:39 UTC by Spinoscythe

Fixes #1188

This was just a TODO left during porting to 1.20.5

2024-06-26 23:27 UTC, thomasglasser commented
Wouldn't ArrowShotEvent or ArrowFiredEvent be a better name for it 🤔 ArrowLoose sounds weird. Not the point of the PR ik but I thought I'd suggest a rename.

2024-06-26 23:29 UTC, thomasglasser commented
Actually it fires for bows no matter what the item is, which may not always be an arrow. BowShotEvent or BowFiredEvent would be better

2024-06-30 21:13 UTC, NewJumper commented
or possibly rename it to `ProjectileFireEvent` to better match with the existing `ProjectileImpactEvent`?

2024-06-30 21:14 UTC, thomasglasser commented
See that doesn't work bc it doesn't fire for every projectile, it fires from BowItem

2024-06-30 23:27 UTC, NewJumper commented
oh yea, that's true

2024-07-02 20:15 UTC, sciwhiz12 requested changes
Patching the line with the `instanceof ServerLevel` is incorrect. While it prevents the arrow projectile from being spawned, it does not prevent the sound effect, the increment of the statistic, and the projectile item being consumed from the inventory. 

(This should have been tested by adding an always-cancelling listener, which can be mimicked by modifying the `EventHooks` method to always return `-1`.)

The correct place to hook would be just after the `getUseDuration` call, in order to avoid those side-effects I mentioned above, and following the original patch [as seen in 1.20.5](https://github.com/neoforged/NeoForge/blob/8ef74db358eb212361b84b2d671695b983426935/patches/net/minecraft/world/item/BowItem.java.patch#L8-L10).

2024-07-02 20:17 UTC, sciwhiz12 commented
> Wouldn't ArrowShotEvent or ArrowFiredEvent be a better name for it 🤔

I would assume the name was decided to be the twin for `ArrowNockEvent`, which handles the bow being first drawn. (As to why they are not called `BowDrawnEvent` and `BowFiredEvent`, I don't exactly know.)

2024-07-03 08:35 UTC, HenryLoenwind commented
> I would assume the name was decided to be the twin for `ArrowNockEvent`, which handles the bow being first drawn.

That event name is at least 11.5 years old; i.e. it dates back to the time when there was only a bow and a single type of arrow. So, while the Nock event is its twin, the name was chosen because it properly fit back then.

2024-07-03 09:06 UTC, Spinoscythe commented on patches/net/minecraft/world/item/BowItem.java.patch
> ++                        player,
Oopsie or not?

2024-07-03 09:11 UTC, Spinoscythe commented on patches/net/minecraft/world/item/BowItem.java.patch
> ++                        player,
it isn't. phew

2024-07-03 09:47 UTC, Spinoscythe commented on patches/net/minecraft/world/item/BowItem.java.patch
> ++                        player,
wait it is

2024-07-03 13:20 UTC, sciwhiz12 requested changes
Seems to work in my testing.

You need to clean up your patches. Re-add back unnecessarily removed blank lines, avoid renaming local variables without reason, etc.

2024-07-03 13:20 UTC, sciwhiz12 commented on patches/net/minecraft/world/item/BowItem.java.patch
> ++
Revert the change to the `ServerLevel` variable name (to the original `serverlevel`; note the capitalization of the middle L).

2024-07-03 13:20 UTC, sciwhiz12 commented on patches/net/minecraft/world/item/BowItem.java.patch
> +-
Add this blank line back.

2024-07-03 17:31 UTC, HenryLoenwind approved these changes

2024-07-04 09:07 UTC, sciwhiz12 approved these changes

2024-07-04 09:07 UTC, merged