Expose getters on ShapedRecipe class
neoforged/NeoForge pull request #1270
Opened 2024-07-09 11:20 UTC by TelepathicGrunt

Adds a getter for pattern and result fields for easier serialization by modders. The result getter is because the original one requires a Provider param and someone's worry was passing null might crash other mods or mojang starts using Provider in future in a non-null safe way.

2024-07-10 11:48 UTC, Matyrobbrt requested changes
I don't think we should be introducing anything that involves bypassing Mojang's registry access API, especially as more and more methods require it.

What is the use case for the `result` field AT? If you need to copy a shaped recipe and reuse the codec, a registry access is available during deserialization.

2024-07-10 22:28 UTC, TelepathicGrunt commented
@Matyrobbrt Removed result AT. Only have pattern AT now as that has no getter at all. I think that should be fine.

2024-07-11 11:23 UTC, Minecraftschurli approved these changes

2024-07-11 11:37 UTC, Matyrobbrt approved these changes

2024-07-11 14:20 UTC, merged