Add `ServerLevelEvent.CustomSpawners` event
neoforged/NeoForge pull request #1272
Opened 2024-07-10 02:39 UTC by RaymondBlaze

Closes #1243.
Introduced the `ServerLevelEvent.CustomSpawners` event for modifying `ServerLevel#customSpawners`.
Unlike the proposal in #1243, this PR uses a simpler implementation, mods subscribing the event may access a fully initialized `ServerLevel` instance and modify the custom spawners list.

2024-07-10 16:51 UTC, Matyrobbrt submitted a review, later dismissed
I'm not exactly keen on introducing yet another event with subclasses prematurely, any reason why the event isn't top level?

2024-07-10 16:51 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/event/level/ServerLevelEvent.java
> +        public List<CustomSpawner> getCustomSpawners() {
You should add a method to add directly in the event class.

2024-07-11 02:25 UTC, RaymondBlaze commented
> I'm not exactly keen on introducing yet another event with subclasses prematurely, any reason why the event isn't top level?

I'm not sure about the convention of introducing nested class events, the premature argue seems fair to me, so I'll move it to the top level.
Just for sure, are you suggesting that `ServerLevelEvent` class shouldn't exist at all, or just `CustomSpawnersEvent` should be top level instead of nested?

2024-07-12 14:25 UTC, Matyrobbrt commented
It shouldn't exist. Alternatively you can make `LevelEvent` generic.

2024-07-14 21:34 UTC, Shadows-of-Fire commented
This event should be a top-level class named either `AddCustomSpawnersEvent` or `RegisterCustomSpawnersEvent` (I leave the choice of name up to you, since we have no concrete guidelines on this feature and events for adding things at server startup are split between `Register` and `Add).  As mentioned, the class `ServerLevelEvent` need not exist.

Do not make `LevelEvent` generic as part of this change, as it will trigger a large unrelated refactor.

2024-07-15 01:05 UTC, RaymondBlaze commented
> This event should be a top-level class named either `AddCustomSpawnersEvent` or `RegisterCustomSpawnersEvent`

I would like to use `ModifyCustomSpawnersEvent` instead, since this event provides full modification to the list (which can be used to remove vanilla custom spawners), while both `Add` and `Register` indicates "add-only".

2024-07-17 19:59 UTC, Spinoscythe requested changes

2024-07-17 19:59 UTC, Spinoscythe commented on src/main/java/net/neoforged/neoforge/event/level/ModifyCustomSpawnersEvent.java
> +    public ModifyCustomSpawnersEvent(ServerLevel serverLevel, List<CustomSpawner> customSpawners) {
mark this constructor as `@ApiStatus.Internal`

2024-07-18 07:03 UTC, Spinoscythe approved these changes
LGTM

2024-07-18 23:42 UTC, TelepathicGrunt approved these changes

2024-07-19 02:53 UTC, merged