Added modifier key states to TooltipFlag
neoforged/NeoForge pull request #1402
Opened 2024-07-31 16:55 UTC by HenryLoenwind

appendHoverText seemingly is a client-only method on Item in which mods regularly will want to check the state of the shift and/or ctrl key. It is easy to write that in a way to crash on classloading on a dedicated server. Also, that method does exist on the server and even though it is only called by client code in vanilla, it is not unreasonable for mods to call it on the server, leading to more crashes.

While this can be circumvented in various ways, all of them are annoying to write and not immediately obvious unless you have run into such a crash before.

This patch makes it less likely that modders write non-server-safe code by providing the state of the modifier keys in the TooltipFlag.

2024-07-31 16:59 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/client/util/NeoTooltipFlag.java
> +public record NeoTooltipFlag(boolean advanced, boolean creative, boolean shiftDown, boolean controlDown, boolean altDown) implements TooltipFlag {
We don't use the `Neo` prefix, and `NeoForge` should be avoided too in favor of something more meaningful. Maybe `ModifierKeysTooltipFlag`.

2024-07-31 22:36 UTC, Technici4n submitted a review, later dismissed

2024-07-31 22:37 UTC, Technici4n commented
Quoting Gizmo from Discord:

> Would it be out of scope for the tooltip flag PR to also pass the client level into the tooltip context?

2024-07-31 23:18 UTC, Technici4n submitted a review, later dismissed

2024-08-05 14:03 UTC, Matyrobbrt requested changes

2024-08-05 14:03 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/client/ClientTooltipFlag.java
> +public record ClientTooltipFlag(boolean advanced, boolean creative, boolean shiftDown, boolean controlDown, boolean altDown) implements TooltipFlag {
Please mark the default constructor as internal.

2024-08-05 14:03 UTC, Matyrobbrt commented on patches/net/minecraft/world/item/TooltipFlag.java.patch
> ++    }
```suggestion
+    /**
+     * Neo: Returns the state of the Control key (as reported by Screen) on the client, or {@code false} on the server.
+     */
+    default boolean hasControlDown() {
+        return false;
+    }
+
+    /**
+     * Neo: Returns the state of the Shift key (as reported by Screen) on the client, or {@code false} on the server.
+     */
+    default boolean hasShiftDown() {
+        return false;
+    }
+
+    /**
+     * Neo: Returns the state of the Alt key (as reported by Screen) on the client, or {@code false} on the server.
+     */
+    default boolean hasAltDown() {
+        return false;
+    }
```

2024-08-05 20:46 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/client/ClientTooltipFlag.java
> +public record ClientTooltipFlag(boolean advanced, boolean creative, boolean shiftDown, boolean controlDown, boolean altDown) implements TooltipFlag {
```suggestion
public record ClientTooltipFlag(boolean advanced, boolean creative, boolean shiftDown, boolean controlDown, boolean altDown) implements TooltipFlag {
    @ApiStatus.Internal
    public ClientTooltipFlag {}
```

2024-08-05 20:59 UTC, Matyrobbrt approved these changes

2024-08-05 20:59 UTC, merged

2025-05-29 12:01 UTC, mezz commented
The way this is implemented is a bit unusual.
Adding helpers here for key modifiers means that mods that use tooltip flags without this wrapper (JEI) will get different tooltips when key modifiers are pressed, because they are defaulted to `false`.

I am wrapping my tooltip flags in this now, but this took a while to be discovered and reported. 
It may be worth thinking about if there's a way to accomplish the same goal but limit the scope so that it doesn't require changing the code of all callers.

2025-05-29 17:42 UTC, HenryLoenwind commented
> It may be worth thinking about if there's a way to accomplish the same goal but limit the scope so that it doesn't require changing the code of all callers.

The only way I see to do that would be to make `Screen.hasShiftDown(), Screen.hasControlDown(), Screen.hasAltDown()` work server-side and give mods the ability to threadlocally override the results of those methods before calling a tooltip-generating method.

It's always the same thing---when you add a new way to get information, everyone who still uses the old way gets left behind. There's no way around it, but not to add a new way and change the old source instead. Sadly, due to the sidedness of the code, that's not a viable solution here. We can't just make a server-side version of `Screen` available so people can keep calling that. The same goes for changing the source of `TooltipFlag`, as annoyingly `TooltipFlag.Default.xxx` are constants and not getter methods we could add logic to. Changing that would be pretty breaking.

One way would be to add code to `TooltipFlag.Default` that detects if it's running on the logical(!) client side and fetch the data in a server-safe way. But that's pretty convoluted when using the "good old" "use separate impl classes for server and client" solution works just fine.

BTW: I had a very casual look at your commit. Is that `SafeIngredientUtil.getTooltip()` only used for rendering or also for searching/search indexing? In the latter case, you may not want to wrap in a `ClientTooltipFlag` as that captures the keyboard state, but either use the default or your own record, which, e.g., reports shift being down. (Being able to index tooltips independently of the actual keyboard state was one of the design goals behind this, even though it's not stated in the reasoning explicitly.)

2025-05-31 02:05 UTC, mezz commented
Thanks for the extra detailed information @HenryLoenwind , I appreciate it.
I will update my implementation with your suggestions, it makes sense to me.

Would it be possible to update the `default` methods so that they return the correct keyboard state when it's safe to?

2025-06-04 16:30 UTC, HenryLoenwind commented
> Would it be possible to update the `default` methods so that they return the correct keyboard state when it's safe to, and `false` on the server?

Probably. However, detecting the *logical* side some code runs on isn't trivial. (Disclaimer: I'm not up to date with mc or neo.) It requires looking at which thread the code runs on and guessing from there. While only code on one specific thread should call `Screen`, making it less of a guess in this case, to my understanding, it's not a thing that should go into neo in the first place.

Also, proper architecture is to capture those values at the time the flag is obtained. There are plenty of exploits in games that are caused by devs thinking people can't let go of a button as quickly as their code can handle the button press. (Same category: Checking a bow's enchantment when the arrow hits instead of when it's fired in Minecraft.) Not that important here, again, but I hate writing generally bad code when it can be avoided.

And again, we're running into some stuff that's only done halfway in mc code. `TooltipFlag.Default.NORMAL` should be `TooltipFlag.Default.getNormal()`. This would avoid all those issues, as now `getNormal()` could be patched. Also, I'm sure there are mods out there that do `if (flag == TooltipFlag.Default.NORMAL)` ...