New translation format system
neoforged/NeoForge pull request #1408
Opened 2024-08-02 18:12 UTC by HenryLoenwind

This is a replacement for #1134 and supersedes #1269.

#1134 was a good idea, but it ran into the issue that its translations are not editable on Crowdin and will even be trashed unless a translator knows exactly what they are dealing with.

This new system doesn't employ json structures but operates on the string contents of a translation. If it starts with a special marker (a sequence that is invalid for vanilla code), the translation string will be parsed by our parser instead.

The format is inspired by html and MiniMessage. It supports:

- Markup for all ChatFormatting styles, e.g. `This is <red>red</red>!`
- Aliases for ChatFormatting: b, i, em, u, o, obf, s, st, grey, dark_grey.
- Parameter insertion, e.g. `<0> <1> <2>`
- ICU plural support, e.g. `<0:plural:one{is # dog} other{are # dogs}>`
- Inclusion of other language keys, e.g. `<ref:other.key>`
- Keybindings, e.g. `<key:key.jump>`
- RGB colours, e.g. `<color:4637>...</color> <color:#FF00FF>...</color>`
- Fonts, e.g. `<font:minecraft:alt>...</font>`

It is intended that this replaces #1134 in the next breaking phase.

2024-08-02 18:18 UTC, HenryLoenwind commented
Here is the monster I've been using to test:

`  "neoforge.configuration.title": "%n <blue>%s</blue><color:#7700ff00>gr<underline>e<key:key.jump>e</underline>n</color> <font:minecraft:alt>f<u>o</u>nt?</font> (There <1:plural:one{is # dog} other{are <blue>#</blue>\\> <italic>dogs</italic>}> here.) <ref:fml.menu.mods.config>",
`

It generates:

![image](https://github.com/user-attachments/assets/7b0e9902-30ee-4462-a376-b59b3ce5cfc8)

open TODOs:

- [ ] %n -> %f. needs a patch to eliminate the error in the json reader
- [ ] I18N/other places that may access the raw language value
- [ ] an automated test
- [ ] convert all json-format keys in neo's langfile (I volunteer)
- [ ] docs
- [ ] other formatters? numbers, dates, spellout, ordinal, duration?
- [ ] report exceptions to the logfile? (vanilla doesn't)
- [ ] other Style attributes? (click, hover, insert)

2024-08-02 19:43 UTC, Technici4n commented
Thoughts on just having the stringized version of the JSON in a string (with some prefix) instead of this complicated alternative syntax? (Similar to SNBT for recipes before data components).

2024-08-02 19:58 UTC, HenryLoenwind commented
> Thoughts on just having the stringized version of the JSON in a string (with some prefix) instead of this complicated alternative syntax? (Similar to SNBT for recipes before data components).

It wouldn't be less complicated as we cannot simply throw that json back into the parser and have it end up in the language. We'd need to iterate and execute it to produce a list of FormattedText text anyway. And at that point, there's no real advantage anymore. On the other hand, JSON is a pain to edit, whereas this format is much more straightforward. `"<red>Hello <0></red>"` vs `"[{\"text\":\"Hello\",\"color\":\"red\"},{\"index\":0,\"color\":\"red\"}]"`

2024-08-03 07:09 UTC, Technici4n requested changes
I am not convinced that this is a path we want to continue going down.

The Vanilla way to combine translations and formatting is to use substitutions with a different style. We recently accepted a patch that allows entering Components directly in the lang file, reusing the established syntax for Components. Unfortunately, that doesn't play nicely with Crowdin translations. At this point, we have two options:

1. Stick to String-only translations and apply the formatting using parameter substitutions.
2. Invent a completely custom format that plays better with Crowdin.

I think that 1. is the correct technical choice from a simplicity and consistency point of view. This PR proposes 2., as such I am against it.

2024-08-05 13:07 UTC, lukebemish commented
Correct me if I'm wrong, but the parameters substitution approach Techni4n mentions requires stuff on the code end, does it not? Thus, it is not viable for translations where the key and how it is consumed are all generated based on some RL on the vanilla end -- which is a majority of translations! Furthermore, this system seems to support stuff like the plural setup that is _much_ more complicated, if not impossible, to handle on that end as how it works varies by language. You simply _cannot_ define it via a substitution like that -- you need language-specific logic. As such, what Techni4n proposed as option 1 is just not a viable option for solving the issues this PR solves -- whether or not this PR is the right approach to solving those issues.

2024-08-05 15:58 UTC, Technici4n commented
I find your assessment that option 1 is not viable... interesting... considering that Minecraft is using it just fine.

2024-08-05 16:27 UTC, lukebemish commented
The scope of what mods want to do and need to do is far larger than the scope of what vanilla does or needs to do. Your assessment that vanilla is using it just fine is irrelevant when I have pointed out situations it does not work in in the much broader modded context.

2024-08-05 16:56 UTC, TelepathicGrunt commented
@lukebemish if we are going to drag in mods as an excuse, then we should be asking for real in-use examples of actual mods that need a different system than what vanilla does. If vanilla can handle the other languages without much issues in translating, then it seems unlikely that a modder would need to deviate heavily. Heck, there might not be any modders whose mod will live and die by special casing rules translations.

We can speak in hypotheticals all day and nothing gets merged or changed or cleaned up. Hence why if it is going to be argued that a system must be kept/used by modders, let’s get some actual examples of people who need a different system than vanilla’s

2024-08-05 17:00 UTC, lukebemish commented
This isn't hypothetical. For a very real use of something like the plural system, see the fluid unit PR which ran into pain here

2024-08-05 21:41 UTC, HenryLoenwind commented
> ends up with at least 3 keys per thing being translated, and doesn't play nice with RL-based translation keys like pop up there.

To support plurals for all languages, you need _6_ translation keys.

Vanilla doesn't have any translation string for normal gameplay that has a number in a sentence, they worded everything to avoid that. They have some in command output, where they use single values with "item(s)", which is acceptable in English (and Germanic languages in general) but gets really awkward in languages with more complex/more forms.

2025-04-19 10:08 UTC, Matyrobbrt commented
Given the lack of activity and the need for a rebase, I'll be closing this PR for now. Feel free to open it again after the conflicts are resolved.

2025-04-19 10:08 UTC, closed without merging