Add Maty's GameTest gist into Neo repo
neoforged/NeoForge pull request #1416
Opened 2024-08-04 18:15 UTC by TelepathicGrunt

Original gist: https://gist.github.com/Matyrobbrt/832c0d88a90ae15f5f665bb794a48198

Someone should write one for JUnit tests as well for balance, as all things should be

Make sure this is merged with no build made somehow

2024-08-04 18:28 UTC, shartte submitted a review, later dismissed

2024-08-05 11:32 UTC, Matyrobbrt requested changes

2024-08-05 11:32 UTC, Matyrobbrt commented on docs/MCGAMETESTS.md
The name of this file is a tad misleading, I'd name it `TESTFRAMEWORK`.

2024-08-05 11:32 UTC, Matyrobbrt commented on docs/NEOGAMETESTS.md
> +More information can be found [here](MCGAMETESTS.md).
```suggestion
More information can be found [here](MCGAMETESTS.md).
If you're unsure how to write a test for a feature, feel free to ask in our [Discord](https://discord.neoforged.net/) server, in the [`#neoforge-github` channel](https://discord.com/channels/313125603924639766/852298000042164244), or consult the existing tests.
```

2024-08-05 11:32 UTC, Matyrobbrt commented
Please also link the second file in the `CONTRIBUTING.md` file under section 8, a subsection that says something along the lines of "Write an (automated) test under the `tests` project, if possible".

2024-08-05 12:00 UTC, Matyrobbrt commented
Oh also, since this is a documentation update PR, can you also update the readme to mention 1.21 as active support?

2024-08-05 15:23 UTC, Spinoscythe requested changes

2024-08-05 15:23 UTC, Spinoscythe commented on docs/MCGAMETESTS.md
> +  framework.init(FMLJavaModLoadingContext.get().getModEventBus(), ModLoadingContext.get().getActiveContainer());
Remove the reference to FMLJavaModLoadingContext

2024-08-05 22:12 UTC, HenryLoenwind commented
BTW, has someone cross-checked this against https://docs.neoforged.net/docs/misc/gametest/ ? Are they equivalent? Is this a superset (then the website docs should mention this one as further reading)?

2024-08-05 22:15 UTC, TelepathicGrunt commented
@HenryLoenwind Pretend you are making a NeoForge PR and you need to write a gametest. Now look at the Game Test doc. Then the gametest file in this PR. Which one is going to set you up better for writing a game test?

2024-08-06 02:50 UTC, HenryLoenwind commented
> @HenryLoenwind Pretend you are making a NeoForge PR and you need to write a gametest. Now look at the Game Test doc. Then the gametest file in this PR. Which one is going to set you up better for writing a game test?

Clearly the doc. It's the only one of the two that actually tells me how to run the tests.

But that was not my question. The question was if there's anything in this one that is generic and should go into the docs instead to avoid repetition---and here I'm assuming stuff in this one doesn't exist for mods and only neo's dev env, which is something that's not clear from taking a quick look at this one either.

So again, has someone who actually understands this stuff cross-checked this with the docs to eliminate duplications? Is there something in here that would better go into the docs or something that would better reference the docs and explain the differences instead of repeating them?

2024-08-06 10:50 UTC, TelepathicGrunt commented
I find the file here far easier to follow than the docs. The docs broke up the examples too much into piecewise and I can't follow them any more and have no idea how any of the gametest is put together. The example here is more complete and actually shows the context of how it is put together. That is my opinion.

2024-08-07 22:06 UTC, Matyrobbrt approved these changes

2024-08-07 22:07 UTC, merged