[1.21] Allow for custom components in enchantment datagen
neoforged/NeoForge pull request #1421
Opened 2024-08-05 06:56 UTC by Shadows-of-Fire

Enchantment stores a full `Component` for the `description` field, which allows specifying more complex names than simple text via datapack.  However, Mojang did not expose such functionality through `Enchantment.Builder`. This PR adds the ability to customize the name component without needing to subclass and AT `Enchantment.Builder`.

Example usage:
```java
register(context, Ench.Enchantments.CHAINSAW,
    Enchantment.enchantment(
        Enchantment.definition(
            items.getOrThrow(ItemTags.AXES),
            1, // weight
            1, // max level
            Enchantment.constantCost(55),
            Enchantment.constantCost(200),
            10, // anvil cost
            EquipmentSlotGroup.MAINHAND))
        .withCustomName(c -> c.withStyle(ChatFormatting.DARK_GREEN)) // Additional custom name functionality
        .withEffect(Ench.EnchantEffects.CHAINSAW));
```

2024-08-26 16:23 UTC, sciwhiz12 requested changes
Looks generally fine. Just one thing that seems questionable.

That `TODO` on line 50 of the patch ought to be looked into...

2024-08-26 16:23 UTC, sciwhiz12 commented on patches/net/minecraft/world/item/enchantment/Enchantment.java.patch
> ++        protected java.util.function.UnaryOperator<MutableComponent> nameFactory = java.util.function.UnaryOperator.identity();
Why is this `protected`?

2024-09-17 18:55 UTC, Shadows-of-Fire commented on patches/net/minecraft/world/item/enchantment/Enchantment.java.patch
> ++        protected java.util.function.UnaryOperator<MutableComponent> nameFactory = java.util.function.UnaryOperator.identity();
Since this is a patched-in field, it cannot be AT'd, and making it private would make subclassing `Enchantment.Builder` impossible.

2024-10-06 02:32 UTC, sciwhiz12 approved these changes

2024-10-06 02:35 UTC, merged