Add ServerEntitySendDirtyEntityDataEvent
neoforged/NeoForge pull request #1445
Opened 2024-08-12 19:34 UTC by TT432

2024-08-12 19:42 UTC, TelepathicGrunt commented
Can you fill out the description here with why this event is needed and problem it solves for what use case?

2024-08-12 19:43 UTC, TelepathicGrunt requested changes

2024-08-12 19:43 UTC, TelepathicGrunt commented on src/main/java/net/neoforged/neoforge/event/EventHooks.java
The import and spacing changes here caused by your ide settings probably should be undone since it isn’t really part of yor pr’s changes

2024-08-12 22:24 UTC, XFactHD requested changes
How is this different from an `EntityTickEvent.Post` listener checking for dirty data and sending the custom packet?

2024-08-12 22:45 UTC, TT432 commented
> How is this different from an `EntityTickEvent.Post` listener checking for dirty data and sending the custom packet?这与检查脏数据并发送自定义数据包的`EntityTickEvent.Post`侦听器有何不同？

With different frequencies, behavior is closer to the vanilla.

2024-08-13 06:13 UTC, HenryLoenwind commented on src/main/java/net/neoforged/neoforge/event/EventHooks.java
> +        NeoForge.EVENT_BUS.post(new ServerEntitySendDirtyEntityDataEvent(entity, serverEntity));
Please don't swap the parameter order without a reason.

2024-08-13 06:16 UTC, HenryLoenwind commented
Is this for modded entities or for attaching to vanilla entities and entities from other mods?

If it's the former, a callback to a method in IEntityExtension would be cheaper than posting an event. For the latter, yes, an event is the right thing.

2024-08-13 06:24 UTC, TT432 commented
> Is this for modded entities or for attaching to vanilla entities and entities from other mods?
> 
> If it's the former, a callback to a method in IEntityExtension would be cheaper than posting an event. For the latter, yes, an event is the right thing.

for all entities

2024-08-13 12:36 UTC, XFactHD commented
> With different frequencies, behavior is closer to the vanilla.

I'm not totally sure what you mean by this, but the timing difference between the event you are adding and the existing tick event is irrelevant for network sync, the packets are handled completely separately on the client anyway. Can you give a more detailed explanation why you need it to fire specifically from this place instead of a generic entity tick event handler?

2024-09-27 03:01 UTC, closed without merging

2024-09-27 03:01 UTC, Shadows-of-Fire commented
I do not believe this event provides any functionality that cannot be accomplished via the `EntityTickEvent`.