[1.21] Add NamespacedDirectoryLister
neoforged/NeoForge pull request #1488
Opened 2024-08-25 00:37 UTC by XFactHD

This PR adds the `NamespacedDirectoryLister`, a namespace-aware version of vanilla's `DirectoryLister` sprite source.
The motivation behind that is the regular occurence of mods adding textures to a generic, high-traffic directory (common examples are `textures/model(s)/` and `textures/entity/`) and then using a `DirectoryLister` (which is not namespace-aware and will collect files in the specified directory and sub-directories thereof from all namespaces) to stitch their textures to the block atlas. When this is done for directories like the two examples (especially the latter) which often contain entity-style texture maps which that a very large footprint, then the block atlas quickly gets blown up to absurd sizes, sometimes even blowing past texture size limits of certain GPUs (8k<sup>2</sup> for older GPUs, 16k<sup>2</sup> for the large majority of GPUs and 32k<sup>2</sup> for only the latest Nvidia GPUs) when a lot of mods or particularly big mods (in terms of textures in the affected directories) are involved.
It's worth noting that patching the vanilla `DirectoryLister` sprite source to be namespace-aware by default (i.e. without adding an optional namespace parameter) is not an option for two reasons:
1. A sprite source does not know which resource pack it came from and funneling that data through is painful ([ask me how I know](https://www.curseforge.com/minecraft/mc-mods/atlasviewer))
2. Even if it were aware of its origin, doing so would break any and all assumptions about `textures/block/` and `textures/item/` working out of the box on the block atlas (the same of course applies to basically all other atlases as well) and would therefore break all mods and resourcepacks that place textures in these directories outside of the vanilla namespace.

---

I also took the liberty to make the `RegisterSpriteSourceTypesEvent` less of a pain to use as there is no reason to not construct the `SpriteSourceType` outside the event since it's just a paper-thin wrapper around the codec. The current implementation makes storage and use of the type unnecessarily annoying.

2024-08-25 03:29 UTC, sciwhiz12 requested changes

2024-08-25 03:29 UTC, sciwhiz12 commented on src/main/java/net/neoforged/neoforge/client/event/RegisterSpriteSourceTypesEvent.java
> +        this.types.put(id, sourceType);
Shouldn't this do the check against duplicate sprite source registration, as the now-deprecated method does?

2024-08-25 03:29 UTC, sciwhiz12 commented on src/main/java/net/neoforged/neoforge/client/textures/NamespacedDirectoryLister.java
> +    @Override
Please add a blank line between the field and the method.

2024-08-25 03:32 UTC, XFactHD commented on src/main/java/net/neoforged/neoforge/client/event/RegisterSpriteSourceTypesEvent.java
> +        this.types.put(id, sourceType);
Yes, it definitely should

2024-08-25 03:33 UTC, XFactHD commented on src/main/java/net/neoforged/neoforge/client/textures/NamespacedDirectoryLister.java
> +    @Override
I can't, just as I can't remove the empty line between the record header and the first field, blame Spotless.

2024-08-25 07:11 UTC, Matyrobbrt requested changes

2024-08-25 07:11 UTC, Matyrobbrt commented on tests/src/main/java/net/neoforged/neoforge/debug/client/ClientTests.java
> +    @TestHolder(description = "Tests that the NamespacedDirectoryLister only collects resources from the specified namespace")
This test should be marked as enable by default for the fail/pass to actually work.

2024-08-26 16:39 UTC, sciwhiz12 approved these changes
Looks fine to me, and the test passes. Waiting on @Matyrobbrt to review the changes to the test framework.

2024-08-27 08:33 UTC, Matyrobbrt approved these changes

2024-08-27 10:22 UTC, merged