feat: Add drawShadow support to drawCenteredString methods
neoforged/NeoForge pull request #1493
Opened 2024-08-26 22:00 UTC by baileyholl

2024-08-30 18:34 UTC, XFactHD requested changes

2024-08-30 18:34 UTC, XFactHD commented on patches/net/minecraft/client/gui/components/AbstractWidget.java.patch
> ++            GuiGraphics p_281620_, Font p_282651_, Component p_281467_, int p_283621_, int p_282084_, int p_283398_, int p_281938_, int p_283471_, boolean dropShadow
More of a nitpick, but can you re-order these overloads like this:
- Original 8-param method
- 8-param method with added shadow parameter
- Original 9-param method
- 9-param method with added shadow parameter

This should make the patch a bit easier to read

2024-08-30 18:34 UTC, XFactHD commented on src/main/java/net/neoforged/neoforge/client/extensions/IGuiGraphicsExtension.java
> +    default void drawCenteredString(Font font, Component p_282456_, int x, int y, int color, boolean dropShadow) {
Please use a proper name for the `Component` parameter

2024-08-30 18:34 UTC, XFactHD commented on src/main/java/net/neoforged/neoforge/client/extensions/IGuiGraphicsExtension.java
> +    default void drawCenteredString(Font font, FormattedCharSequence p_281854_, int x, int y, int color, boolean dropShadow) {
Please use a proper name for the `FormattedCharSequence` parameter

2025-04-19 09:56 UTC, Matyrobbrt commented
Given the lack of activity and the need for a rebase, I'll be closing this PR for now. Feel free to open it again after the conflicts are resolved.

2025-04-19 09:56 UTC, closed without merging