Add a method for `HangingSignBlock` to `BlockStateProvider`
neoforged/NeoForge pull request #1511
Opened 2024-09-03 21:29 UTC by ZestyBlaze

The method `BlockStateProvider.signBlock` does not support usages for data generating `HangingSignBlock`s. 
This PR just adds a pair of methods in the same fashion as `BlockStateProvider.signBlock` that allow you to create the files from either a `ResourceLocation` or a `ModelFile`
No game tests because the only game tests I could find were `oldTests`?

If anything else needs adding, let me know, this is my first PR for NeoForge :)

2024-09-03 21:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=1511) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/neoforged/NeoForge?pullRequest=1511) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neoforged/NeoForge?pullRequest=1511) it.</sub>

2024-09-08 21:16 UTC, sciwhiz12 requested changes
The added methods look fine, but we do need to add a test for this in `DataGeneratorTest`. In that class, find the call to `signBlock`, and add the following underneath it:

```java
hangingSignBlock((CeilingHangingSignBlock) Blocks.ACACIA_HANGING_SIGN, (WallHangingSignBlock) Blocks.ACACIA_WALL_HANGING_SIGN, blockTexture(Blocks.STRIPPED_ACACIA_LOG));
```

That line will make the test mod generate files for the acacia hanging sign. (Don't forget to commit the generated files.) The test mod has code to ensure that the generated files match their vanilla counterparts.

2024-09-09 00:22 UTC, ZestyBlaze commented
I thought so! I actually did look at the signBlock and find the tests but it was under a package called `oldtests` and wasn't sure how to run the test because the ones in the docs weren't running it

2024-09-09 08:32 UTC, sciwhiz12 approved these changes

2024-09-09 20:14 UTC, closed without merging