Add a few new `ItemModelProvider` methods!
neoforged/NeoForge pull request #1542
Opened 2024-09-14 13:55 UTC by ZestyBlaze

Since `ItemModelProvider` only provides `basicItem` which does exactly what it does on the tin, when having to do other items that require something a bit different, such as handheld items or any item that supports a template from Minecraft or your own mod, it requires the developer to write a custom method just to handle these item models or hand write them
This PR adds two new methods at the moment, `handheldItem` and `spawnEggItem`, however this PR will be marked as draft for a while awaiting community input for more devs to suggest other useful methods they might like to see \:)

2024-09-23 22:38 UTC, ZestyBlaze commented
New method added, PR is ready for review

2024-10-06 00:39 UTC, XFactHD requested changes
This has been sitting long enough, if anyone comes up with further ideas, then a new PR is always an option.
One minor nitpick, then it's good to go.

2024-10-06 00:39 UTC, XFactHD commented on src/main/java/net/neoforged/neoforge/client/model/generators/ItemModelProvider.java
> +    public ItemModelBuilder simpleBlockItem(ResourceLocation item) {
```suggestion
    public ItemModelBuilder simpleBlockItem(ResourceLocation block) {
```

2024-10-06 18:09 UTC, ZestyBlaze commented
@XFactHD change made to resolve your review

2024-10-06 22:57 UTC, XFactHD requested changes

2024-10-06 22:57 UTC, XFactHD commented on src/main/java/net/neoforged/neoforge/client/model/generators/ItemModelProvider.java
> +        return withExistingParent(item.toString(), ResourceLocation.fromNamespaceAndPath(item.getNamespace(), "block/" + item.getPath()));
The uses of the parameter need to be changed as well.
```suggestion
        return withExistingParent(block.toString(), ResourceLocation.fromNamespaceAndPath(block.getNamespace(), "block/" + block.getPath()));
```

2024-10-07 00:02 UTC, ZestyBlaze commented
Let's ignore how I totally forgot about that and just focus on the fact I've fixed it

2024-10-09 22:19 UTC, XFactHD requested changes
Please commit the generate files from the datagen test

2024-10-10 23:32 UTC, XFactHD approved these changes

2024-10-10 23:33 UTC, merged