Make Biome and Structure Modifiers not crash when attempted to be re-applied
neoforged/NeoForge pull request #1545
Opened 2024-09-15 16:53 UTC by TelepathicGrunt

Basically, the modifiers already know if a biome or structure was modified and ideally should just no-op instead. It doesn't make sense to throw an exception when the exception isn't really helping anyone or preventing any error. Even Commoble, when asked, said there wasn't any strong reason for the exception either
![image](https://github.com/user-attachments/assets/0b9a388d-2a70-4ceb-9346-3e0f1b1e3a4b)

So let's just remove the exception and the modifier do nothing if object was already modified. Basically cleanup. Might allow for more niche use case for the modifiers but they have other issues to deal with on their own when recycling registries. Just NeoForge should be one less roadblock

Closes https://github.com/neoforged/NeoForge/issues/431

2024-09-15 19:01 UTC, sciwhiz12 requested changes

2024-09-15 19:01 UTC, sciwhiz12 commented on src/main/java/net/neoforged/neoforge/common/world/ModifiableBiomeInfo.java
> +            return true;
Adjust the javadoc of this method to match how this method now operates. (It no longer throws an exception, and the biome is only modified on the first invocation of this method.)

2024-09-15 19:01 UTC, sciwhiz12 commented on src/main/java/net/neoforged/neoforge/common/world/ModifiableStructureInfo.java
> +            return;
Adjust the javadoc of this method to match how this method now operates. (It no longer throws an exception, and the biome is only modified on the first invocation of this method.)

2024-09-15 21:27 UTC, sciwhiz12 approved these changes

2024-09-30 11:58 UTC, TelepathicGrunt commented
Time to yolo it

2024-09-30 11:58 UTC, merged