Make Neoforge's Needs Netherite Tool block tag be added to vanilla's incorrect block tags
neoforged/NeoForge pull request #1572
Opened 2024-09-30 12:25 UTC by TelepathicGrunt

Added Javadoc to all the neoforge needs block tags to make it clear what they are for. And makes it so that Needs Netherite actually cause the block to not be mineable by diamond or below

closes https://github.com/neoforged/NeoForge/issues/1571

2024-11-10 21:29 UTC, Shadows-of-Fire commented
Same thing for this one about the double "by default"

2024-11-18 12:40 UTC, sciwhiz12 requested changes

2024-11-18 12:40 UTC, sciwhiz12 commented on src/main/java/net/neoforged/neoforge/common/Tags.java
> +         * By default, this is not added to any Minecraft tag since by default, Wood is in the lowest "tier".
Per @Shadows-of-Fire:
```suggestion
         * By default, this is not added to any Minecraft tag since Wood is in the lowest "tier".
```

2024-11-18 12:40 UTC, sciwhiz12 commented on src/main/java/net/neoforged/neoforge/common/Tags.java
> +         * By default, this is not added to any Minecraft tag since by default, Gold is in the lowest "tier".
```suggestion
         * By default, this is not added to any Minecraft tag since Gold is in the lowest "tier".
```

2024-11-26 15:50 UTC, sciwhiz12 approved these changes

2024-11-26 15:51 UTC, merged