[1.21.3] Sync remaining c tags from Fabric side
neoforged/NeoForge pull request #1628
Opened 2024-10-25 13:06 UTC by TelepathicGrunt

1.21.3 port of https://github.com/neoforged/NeoForge/pull/1593

Note, I did not add any new Pale Garden stuff myself to the tags because those will need special handling to only add to the tags when the user activates the feature flag. Maybe that is better split into a separate PR by someone with more experience with feature flags than me.

---------------
Fabric had some tags that was not in Neo. This PR aims to solve that by importing those tags. Specifically `c:potions` item tag and `c:is_temperate` biome tags. I added the torchflower seeds to `c:seeds/torchflower` and then added that to the `c:seeds` tag as well as it was a missing seed. 

I also improved javadoc for several tags, did some cleanup in a few spots, and marked the `c:is_modified` biome tag as deprecated and for removal in 1.22. Reason being the modified tag was based off of how the old biome layout used to work in the long past. Since Mojang revamped how biomes work, this tag lost all of its meaning and serves no purpose anymore. Hence time to retire it.

The PR to add the tags that are not in Fabric from Neoforge is in this other PR. Discussions ongoing of course: https://github.com/FabricMC/fabric/pull/4161

2024-12-13 14:18 UTC, ageuxo commented on src/generated/resources/assets/c/lang/en_us.json
> +  "tag.item.c.clumps.resin": "Clumps Resin",
shouldn't this be "Resin Clumps" or "Clumps of Resin"?

2024-12-13 14:24 UTC, ageuxo commented on src/generated/resources/assets/c/lang/en_us.json
> +  "tag.item.c.potions.bottle": "Bottle Potions",
This should maybe be "Bottled Potions"?

2024-12-14 22:03 UTC, dhyces requested changes
- Noticed that the Fabric PR used a different translation for "tag.block.c.fences.nether_brick". Neo's is currently "Fences Nether Brick" and the Fabric PR (as well as Neo's item tag) uses "Nether Brick Fences".
- Fabric PR uses singular "Plateau" while Neo is using plural "Plateaus" for "tag.worldgen.biome.c.is_plateau"

2024-12-14 22:03 UTC, dhyces commented on src/main/java/net/neoforged/neoforge/common/Tags.java
> +        public static final TagKey<Item> POTION_BOTTLE = tag("potions/bottle");
Seems like other tags retain the "parent" tag name in their names, ie `CLUMPS_RESIN` or `BRICKS_RESIN`. I think keeping that pattern here makes sense.
```suggestion
        public static final TagKey<Item> POTIONS_BOTTLE = tag("potions/bottle");
```

2024-12-15 03:18 UTC, dhyces submitted a review, later dismissed

2024-12-24 13:36 UTC, TelepathicGrunt commented
Fabric side merged. Will get this merged now

2024-12-24 13:51 UTC, sciwhiz12 approved these changes

2024-12-24 13:51 UTC, merged