Add back getAffectedBlocks to explosion events
neoforged/NeoForge pull request #1647
Opened 2024-10-30 23:13 UTC by jpenilla

2024-10-30 23:30 UTC, XFactHD requested changes

2024-10-30 23:30 UTC, XFactHD commented on patches/net/minecraft/world/level/ServerExplosion.java.patch
> ++    private void hurtEntities(List<BlockPos> blocks) {
The vanilla method needs to be kept, marked as deprecated and forward to the new method with a default value (i.e. empty list in this case).

2024-10-31 01:36 UTC, jpenilla commented on patches/net/minecraft/world/level/ServerExplosion.java.patch
> ++    private void hurtEntities(List<BlockPos> blocks) {
Updated with this change

2024-11-01 09:18 UTC, Technici4n approved these changes

2024-11-02 02:46 UTC, XFactHD approved these changes

2024-11-08 04:57 UTC, merged