Use CommonHooks.getCraftingRemainder #1585
neoforged/NeoForge pull request #1672
Opened 2024-11-08 00:23 UTC by ewoudje

CommonHooks.getCraftingRemainder doesn't get used, and 'destroyed' items were not being destroyed.

I split it over 2 commits, one fixing the actual bug, and the other one making all patches call CommonHooks instead.
I wasn't sure how it would be preferred.

Fixes #1585

2024-11-08 00:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=1672) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/neoforged/NeoForge?pullRequest=1672) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neoforged/NeoForge?pullRequest=1672) it.</sub>

2024-11-08 05:09 UTC, Shadows-of-Fire commented
The patch changes in this PR are unnecessary, you've updated `ItemStack#getCraftingRemainder` to use the hook method, but then patched all the call sites to the hook method anyway. Undo the patch changes.

2024-11-08 22:57 UTC, Shadows-of-Fire commented
Actually, based on further review (and looking at the levels of indirection here), the `CommonHooks` method should just be removed and flattened into the `ItemStack` method entirely.

2024-11-09 19:08 UTC, embeddedt commented
Something feels weird about a method named `getCraftingRemainder` having side effects like firing a destroy item event.

2024-11-09 19:14 UTC, Shadows-of-Fire commented
A little bit, yes; it's not entirely different than how we handle other itemstack extension methods, since the class is `final`. There _is_ one call site where we don't want the event to be fired, in `DataComponentIngredient#display`, so I guess we need to take a different approach here.  Prior to the `SlotDisplay` stuff the only call sites for these methods were in recipe remainder calculation.

2024-11-11 20:45 UTC, ewoudje commented
> Something feels weird about a method named `getCraftingRemainder` having side effects like firing a destroy item event.

I could rename it to `computeCraftingRemainder ` or something alike? makes it more clear that it doesn't just get something.

2024-12-23 15:02 UTC, sciwhiz12 requested changes
This PR needs to be reassessed, in light of the fact that `DataComponentIngredient#display` uses the crafting remainder, which might cause the event to be fired when obtaining the slot display without a player doing any actual crafting.

This probably entails switching uses of `getCraftingRemainder()` in methods that do actual crafting to the hook method, and leaving unmodified the method in the item stack extension.

2025-04-19 10:12 UTC, Matyrobbrt commented
Given the lack of activity, I'll be closing this PR for now. Feel free to open it again after the review comments are resolved.

2025-04-19 10:12 UTC, closed without merging