Add a hook for blocks to suppress a neighboring fluid overlay
neoforged/NeoForge pull request #1690
Opened 2024-11-16 18:33 UTC by embeddedt

This PR introduces a new method `shouldHideAdjacentFluidFace` on blocks that may be overridden to customize the logic for determining when the fluid is visually "compatible" with a neighbor (which stops the water overlay from rendering on a given face). The default implementation matches vanilla behavior.

This can be used to tweak the rendering of transparent blocks underwater (e.g. to implement the "depth glass" effect from Alex's Caves, see photo below for an example). That mod currently uses a mixin to implement the same effect; the goal of this PR is to remove the need for such a mixin.

![277799947-8a0c467c-0251-4269-b323-86d44e5a7d34](https://github.com/neoforged/NeoForge/assets/42941056/5ff26acc-792d-41e1-a271-d1d36eced540)

This is #940 but with the method renamed and the patches updated for 1.21.3.

2024-11-17 23:51 UTC, XFactHD requested changes
Do you mind adding a small test?

2024-11-17 23:51 UTC, XFactHD commented on patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
> ++    @Deprecated // Neo: use overload that accepts BlockState
The comment should be a javadoc comment with the deprecation tag.

2024-11-17 23:51 UTC, XFactHD commented on patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
> ++    public static boolean shouldRenderFace(FluidState p_203169_, BlockState p_203170_, Direction p_203171_, BlockState otherState) {
This method should use proper parameter names since it doesn't need to avoid changing otherwise unmodified vanilla code.

2024-11-17 23:51 UTC, XFactHD commented on src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
> +    default boolean shouldHideAdjacentFluidFace(FluidState adjacentFluid) {
I think it would make sense to also pass through the occluding `Direction` of the block this is being called on.

2024-11-17 23:51 UTC, XFactHD commented on src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
> +    default boolean shouldHideAdjacentFluidFace(BlockState state, FluidState adjacentFluid) {
This should have the same docs as the `BlockState`-level method and both should ideally have some short parameter docs.

2024-11-18 00:02 UTC, embeddedt commented on patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
> ++    public static boolean shouldRenderFace(FluidState p_203169_, BlockState p_203170_, Direction p_203171_, BlockState otherState) {
We don't want to defer to Parchment there?

2024-11-18 01:05 UTC, XFactHD commented on patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
> ++    public static boolean shouldRenderFace(FluidState p_203169_, BlockState p_203170_, Direction p_203171_, BlockState otherState) {
That's a fair point, I completely forgot that JST is a bit less strict when it looks up parameter names to apply to overload methods, though I'm not totally sure this case is actually considered an overload by JST.

2024-11-18 20:29 UTC, XFactHD commented on patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
> ++    public static boolean shouldRenderFace(FluidState p_203169_, BlockState p_203170_, Direction p_203171_, BlockState otherState) {
JST won't recognize this as an overload, so deferring to Parchment won't work in this case: https://discord.com/channels/313125603924639766/1154167065519861831/1307887396364222505

2024-11-23 22:15 UTC, XFactHD approved these changes

2024-11-24 22:48 UTC, merged