more branding tweaks including fox
neoforged/NeoForge pull request #17
Opened 2023-07-16 22:10 UTC by cpw

Update modloader, more branding tweaks

2023-07-16 22:18 UTC, Matyrobbrt submitted a review, later dismissed

2023-07-16 23:04 UTC, pupnewfster reviewed
On the topic of branding I believe [this line](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/minecraftforge/server/console/TerminalHandler.java#L30) should probably be changed to `ForgeSnapshotsMod.BRANDING_NAME` as well

2023-07-17 21:10 UTC, pupnewfster requested changes

2023-07-17 21:10 UTC, pupnewfster commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +            buf.append("NeoForge Mod Loader could not load this save.\n\n")
Shouldn't this be either `Fancy Mod Loader` or just `NeoForge`? Rather than `NeoForge Mod Loader`

2023-07-17 21:10 UTC, pupnewfster commented on src/main/java/net/minecraftforge/registries/GameData.java
> +                String header = "NeoForge Mod Loader detected missing/unknown registrie(s).\n\n" +
Shouldn't this be either `Fancy Mod Loader` or just `NeoForge`? Rather than `NeoForge Mod Loader`

2023-07-17 21:10 UTC, pupnewfster commented on src/main/java/net/minecraftforge/registries/GameData.java
> +                String header = "NeoForge Mod Loader detected missing registry entries.\n\n" +
Shouldn't this be either `Fancy Mod Loader` or just `NeoForge`? Rather than `NeoForge Mod Loader`

2023-07-20 16:04 UTC, pupnewfster approved these changes

2023-07-20 16:31 UTC, merged