Make AttributeTemplate record public
neoforged/NeoForge pull request #1708
Opened 2024-11-26 15:42 UTC by TelepathicGrunt

Allows modders to easily use the main constructor to give an Int2DoubleFunction curve to AttributeTemplate.

Closes https://github.com/neoforged/NeoForge/issues/1691

2024-11-26 16:01 UTC, Matyrobbrt requested changes
Interesting that spotless didn't catch it... please use an AT for both the record and its default constructor as is the case for any access changes.

2024-11-27 08:39 UTC, marchermans approved these changes

2024-11-27 13:00 UTC, embeddedt approved these changes

2024-11-28 07:29 UTC, marchermans commented
@Matyrobbrt Could you re-review this?

2024-11-28 17:38 UTC, Matyrobbrt approved these changes

2024-11-28 17:39 UTC, merged

2025-01-23 18:14 UTC, Matyrobbrt commented
@neoforged/bots backport 1.21.1