Correct a grammatical mistake within SUPPORT.md
neoforged/NeoForge pull request #175
Opened 2023-10-13 10:47 UTC by srcres258

"Both" can't be used as the number of the websites is three, hence change it into "All of the three".

2023-10-13 10:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=175) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/neoforged/NeoForge?pullRequest=175) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neoforged/NeoForge?pullRequest=175) it.</sub>

2023-10-13 19:37 UTC, PlatinPython requested changes
I'd suggest "All three" instead, sounds more natural imo

2023-10-13 21:13 UTC, ChampionAsh5357 commented on docs/SUPPORT.md
> + - **Searching for a repository directly:** You may need to try and find a repository directly on source control sites. The most common ones are [GitHub](https://github.com), [GitLab](https://gitlab.
```suggestion
 - **Searching for a repository directly:** You may need to try and find a repository directly on source control sites. The most common ones are [GitHub](https://github.com), [GitLab](https://gitlab.com), and [BitBucket](https://bitbucket.org). Each comes with search capabilities, so simply try to search for the mod's name.
```

2023-10-13 21:14 UTC, ChampionAsh5357 commented on docs/SUPPORT.md
> + - **Searching for a repository directly:** You may need to try and find a repository directly on source control sites. The most common ones are [GitHub](https://github.com), [GitLab](https://gitlab.
I don't know why we're specifying a number instead of making it agnostic.

2023-11-04 02:47 UTC, sciwhiz12 approved these changes

2023-11-04 02:47 UTC, merged