Update issue_report.md (Forge -> NeoForge)
neoforged/NeoForge pull request #178
Opened 2023-10-13 16:23 UTC by Lolothepro

2023-10-13 16:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=178) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/neoforged/NeoForge?pullRequest=178) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neoforged/NeoForge?pullRequest=178) it.</sub>

2023-10-30 19:08 UTC, pupnewfster requested changes
Can you please also update the label from `Triage` to `triage` as it seems those are case sensitive, and then as part of this PR change the `feature_request.md` format to have the label be `enhancement` instead of `Feature`

2023-10-30 19:11 UTC, Lolothepro commented
> Can you please also update the label from `Triage` to `triage` as it seems those are case sensitive, and then as part of this PR also change the `feature_request.md` format to have the label be `enhancement` instead of `Feature`

like this?

2023-10-30 19:30 UTC, pupnewfster approved these changes

2023-10-30 19:31 UTC, merged