Let vanilla try to handle Container interactions before checking for item handlers
neoforged/NeoForge pull request #1787
Opened 2024-12-18 23:56 UTC by Technici4n

Move our `IItemHandler` interaction hooks after vanilla checks for `Container` interactions. This gives vanilla control over interactions with `Container`s. Fixes #1750. Fixes #1770. (Did not test the latter but I assume it gets fixed).
As a side effect, this greatly simplifies our hooks since we don't need to handle vanilla edge cases such as hopper - hopper interactions having special interactions when it comes to cooldowns.

## Breaking change
Modders need to be careful that their `Container`s will be interacted with as `Container`s before an item handler is even attempted to be found. I'd suggest not implementing `Container` directly on block entities to avoid this problem. Nevertheless, this counts as a breaking change.

## Lookup order
Currently, `Container` entities are preferred over `IItemHandler` blocks. What do people think about that?

Current order: `Container block > Container entity > IItemHandler block > IItemHandler entity`.

I think that it would be preferable to check in this order: `Container block > IItemHandler block > Container entity > IItemHandler entity`.

2024-12-23 17:45 UTC, 2No2Name commented
Confirmed to fix https://github.com/neoforged/NeoForge/issues/1750
Also the measurements for https://github.com/neoforged/NeoForge/issues/1770
(1671 for vanilla, 1201 for Neo w/o fix, 1805 for Neo w/ fix) posted on discord suggest that this PR fixes https://github.com/neoforged/NeoForge/issues/1770 as well.

2024-12-24 02:33 UTC, sciwhiz12 commented
> Currently, `Container` entities are preferred over `IItemHandler` blocks. What do people think about that?
> 
> Current order: `Container block > Container entity > IItemHandler block > IItemHandler entity`.
> 
> I think that it would be preferable to check in this order: `Container block > IItemHandler block > Container entity > IItemHandler entity`.

How difficult would that be to implement? I can see what you mean by that being preferrable -- ensuring that blocks are always checked before entities in either case -- but I wonder how the impl. look like if you have to interweave the item handler check between container blocks and entities.

2024-12-24 10:16 UTC, Technici4n commented
I managed to implement it locally and am planning to update the PR tomorrow.

2024-12-25 07:32 UTC, Technici4n commented
PR updated with a more modder-friendly lookup order. :smile: @sciwhiz12

2025-01-02 14:06 UTC, sciwhiz12 requested changes

2025-01-02 14:06 UTC, sciwhiz12 commented on src/main/java/net/neoforged/neoforge/items/VanillaInventoryCodeHooks.java
>       * Copied from TileEntityHopper#captureDroppedItems and added capability support
Might as well update the referenced method in the comments. Same suggestion for the rest of the comments in this class, insofar as updating references to methods or classes; up to you if you want to pursue rewriting the comments in general.

2025-01-02 14:06 UTC, sciwhiz12 commented on patches/net/minecraft/world/level/block/entity/HopperBlockEntity.java.patch
> ++    @Deprecated
Why was only this method deprecated? Why not the other `getContainerAt` overload, or `getSourceContainer`, or other nearby methods that work with `Container`?

2025-01-02 14:06 UTC, sciwhiz12 commented on src/main/java/net/neoforged/neoforge/items/ContainerOrHandler.java
> +        @Nullable IItemHandler itemHandler) {
Should we enforce through the canonical constructor that either of the two components but not both must have a value? That's the implication of the name, at least.

2025-01-02 14:26 UTC, Technici4n commented on patches/net/minecraft/world/level/block/entity/HopperBlockEntity.java.patch
> ++    @Deprecated
I only deprecated the public one, but I can deprecate all of them if you want.

2025-01-02 14:29 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/items/ContainerOrHandler.java
> +        @Nullable IItemHandler itemHandler) {
Yes, why not!

2025-01-02 14:29 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/items/VanillaInventoryCodeHooks.java
>       * Copied from TileEntityHopper#captureDroppedItems and added capability support
OK, I replaced these two comments by an explanation of what each method does.

2025-01-02 14:41 UTC, sciwhiz12 commented on patches/net/minecraft/world/level/block/entity/HopperBlockEntity.java.patch
> ++    @Deprecated
Ah right, the other methods are `private`. Do we think it is likely that a mod might access-transform any of those methods to being `public` for their use? If not, we can just deprecate the `public` one and leave it at that.

2025-01-02 14:44 UTC, Technici4n commented on patches/net/minecraft/world/level/block/entity/HopperBlockEntity.java.patch
> ++    @Deprecated
I think it's unlikely that a modder would access-transform another of these methods without noticing that Minecraft doesn't use them anymore, and that the `public` `getContainerAt` overload is deprecated.

2025-01-04 11:35 UTC, sciwhiz12 approved these changes

2025-01-04 11:35 UTC, merged