[1.20.x] Pull `EntityEvent$Size` changes from MCF/1.20.x
neoforged/NeoForge pull request #22
Opened 2023-07-18 07:09 UTC by Shadows-of-Fire

This PR is a subset of #14 which pulls in all commits relating to `EntityEvent$Size`, and https://github.com/MinecraftForge/MinecraftForge/pull/9428 which depends on the commit history of those changes.

2023-07-18 15:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=22) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/neoforged/NeoForge?pullRequest=22) before we can accept your contribution.<br/>**0** out of **4** committers have signed the CLA.<br/><br/>:x: Meldexun<br/>:x: ChampionAsh5357<br/>:x: LexManos<br/>:x: Jonathing<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neoforged/NeoForge?pullRequest=22) it.</sub>

2023-07-18 18:51 UTC, pupnewfster requested changes

2023-07-18 18:51 UTC, pupnewfster commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> -    }
These two methods should be reinstated and deprecated for removal as removing them is a breaking change (and also definitely [affects](https://gist.github.com/Pewmaymen/2d9ae4bacb9a128aae8f914f8008b010) mods)

2023-07-19 17:46 UTC, mcg-anon commented
> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=22) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/neoforged/NeoForge?pullRequest=22) before we can accept your contribution.**0** out of **4** committers have signed the CLA.x Meldexunx LexManosx ChampionAsh5357x JonathingYou have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neoforged/NeoForge?pullRequest=22) it.

I don't think that LexManos is going to sign your CLA, just saying.

2024-01-15 03:30 UTC, TheCurle commented
This looks like it could solve one of the issues I was having with gravity wells in one of my mods.
However, those commits will cause a problem with our CLA. We should try to reimplement them in a new (better!) way. And also fix those merge conflicts.

I'll leave this open until I (or someone else) gets around to that.

2024-01-15 03:35 UTC, pupnewfster commented
I believe the entire event will likely become redundant in 1.20.5, so may not be worth the effort.

2024-01-15 03:37 UTC, TheCurle commented
Do note that this is (was?) a 1.20.1 PR. It should be retargeted as such, if 1.20.5 does fix these issues.

2024-01-15 03:39 UTC, pupnewfster commented
No I mean mojang is adding a scale attribute to 1.20.5 so when that releases I doubt we will have a use case for this event.

2024-01-15 03:53 UTC, Shadows-of-Fire commented
Yeah I think we can just toss this one in favor of the scale attribute.  Its all the size event was for anyway.

2024-01-15 03:53 UTC, closed without merging

2024-01-15 03:53 UTC, TheCurle commented
We will; in 1.20.1, where this PR lives. It targets the 1.20.x branch because there was no 1.20.1 branch at its time of creation.

2024-01-15 03:53 UTC, TheCurle commented
That works too. :P