New event: ClientPauseUpdateEvent
neoforged/NeoForge pull request #315
Opened 2023-12-02 01:53 UTC by SrRapero720

Simple hook fired when game pause is updated (``Minecraft#paused``)
Simple explanation of why this event: https://github.com/MinecraftForge/MinecraftForge/pull/9763#issuecomment-1783904855

2023-12-02 01:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=315) <br/>All committers have signed the CLA.

2023-12-02 02:19 UTC, SrRapero720 commented
fixed spotless... meh

2023-12-08 21:02 UTC, Matyrobbrt requested changes, later dismissed
I dislike the name of the event considering that it fires when "the state of pause" is *updated*. I would suggest `ClientPauseUpdatedEvent`. Additionally, the javadocs have several grammatical errors (such as the missing several determiners)

2023-12-11 12:34 UTC, Technici4n approved these changes

2023-12-11 12:35 UTC, merged