[1.20.x] Fix Reach Issues
neoforged/NeoForge pull request #346
Opened 2023-12-09 01:37 UTC by Shadows-of-Fire

This PR addresses #243 and other reach changes that should have been fixed in porting.  It also fixes issues with the eclipse compiler that were introduced by #73

2023-12-09 01:49 UTC, Technici4n requested changes, later dismissed
You should use a proper compiler instead of making changes to the NeoForge source code due to its limitations.

2023-12-09 01:51 UTC, Shadows-of-Fire commented
Like it or not, we support eclipse, so we have to be compatible with the eclipse compiler.

2023-12-09 04:16 UTC, sciwhiz12 commented
At some point, we ought to add some automated check to compile with the Eclipse compiler. Though that may be somewhat difficult, given how hardcoded Gradle seems to be with using a `javac` executable for compilation.

2023-12-12 11:30 UTC, Technici4n reviewed
OK this looks good. Just one thing.

2023-12-12 11:30 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/extensions/IPlayerExtension.java
> +     * The entity reach is increased by 2 for creative players, unless it is currently zero, which disables attacks and entity interactions.
Can you update the comment on `ENTITY_REACH` in `NeoForgeMod` as well?

2023-12-13 09:13 UTC, Technici4n approved these changes

2023-12-13 09:22 UTC, merged