Added trident throw and brushing tool actions
neoforged/NeoForge pull request #351
Opened 2023-12-10 01:47 UTC by TelepathicGrunt

Also updated javadoc for fishing rod cast and shield block tool actions.

Resolves: https://github.com/neoforged/NeoForge/issues/190

2023-12-10 01:48 UTC, TelepathicGrunt commented
hang on forgot patch

2023-12-10 01:57 UTC, TelepathicGrunt commented
Ready for review now

2023-12-16 18:09 UTC, Matyrobbrt requested changes

2023-12-16 18:09 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/common/ToolActions.java
> +     * Have item return this tool action to have damage blocking be active when item is currently being "used".
```suggestion
     * Items should expose this tool action in order to enable damage blocking when the item is being "used".
```

2023-12-16 18:31 UTC, Matyrobbrt approved these changes

2023-12-16 18:36 UTC, merged