Add `neoforge:alternatives` to conditional codecs
neoforged/NeoForge pull request #436
Opened 2023-12-28 13:41 UTC by Matyrobbrt

This PR adds a `neoforge:alternatives` list to conditional codecs, that will try to find an alternative to load by checking the conditions of each one, in order and if they match return the object.  
To achieve that the `WithConditions` record has been made into a sealed class, and a new `ConditionalObject` children has been added. When a `ConditionalObject` is detected at the root, the encoder will write its alternatives.  
Only the root object can have alternatives, and an alternative cannot be of the type `ConditionalObject`.

2023-12-28 14:36 UTC, marchermans approved these changes
I very much approve of this design!

2023-12-28 14:56 UTC, Technici4n requested changes
The datagen is grossly implemented, and we need to make sure the format makes sense as well.

2023-12-28 15:12 UTC, marchermans commented
> The datagen is grossly implemented, and we need to make sure the format makes sense as well.

With respect to the datagen: do you mean the api surface or the actual inner implementation that is hidden from the modder?

2023-12-28 17:01 UTC, KnightMiner commented
To be clear on the behavior, if the root object fails it's conditions, then each alternative is tried one at a time until an object passes, otherwise the object is skipped entirely? In other words, alternatives is strictly a fallback, it's never considered first?

The one functionally conditional recipes had that this lacks is the ability to apply a condition to all alternatives, as before the outer condition skipped the entire loader while the inner one skipped the alternative in favor of the next. Not sure this is needed functionally, just a difference in behavior that stood out.

Also worth asking, what happens if alternatives is present when condition is absent? I assume alternatives would do nothing, may be worth making that a parsing error.

2023-12-28 17:16 UTC, Matyrobbrt commented
> To be clear on the behavior, if the root object fails it's conditions, then each alternative is tried one at a time until an object passes, otherwise the object is skipped entirely? In other words, alternatives is strictly a fallback, it's never considered first?

That's correct. And yes, when there's no condition in the outer alternatives will not be considered, so maybe it should be an error indeed.

2023-12-29 10:20 UTC, Technici4n requested changes

2023-12-29 10:20 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalObject.java
> +public final class ConditionalObject<A> extends WithConditions<A> {
Unnecessary use of inheritance, the alternatives can be part of the parent class, right?

2023-12-29 10:20 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
> +        public <T> DataResult<T> encode(Optional<WithConditions<A>> input, DynamicOps<T> ops, T prefix, boolean supportsAlternatives) {
What is the point of this boolean parameter?

2023-12-29 10:20 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
> +    public static final String ALTERNATIVES_KEY = "neoforge:alternatives";
How these two fields interact with each other should be discussed clearly. IMO, combining the two in the same object makes everything confusing.

2023-12-29 10:20 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
> +                final var alt = ops.listBuilder();
First time I see someone actually use `final var`. There's no point adding `final` everywhere like that.

2023-12-29 10:20 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/crafting/ConditionalRecipeOutput.java
> -@ApiStatus.Internal
This class should ideally remain internal and immutable. I designed it to be usable for multiple recipes. It should be possible to make a separate `ConditionalRecipeBuilder` or something like that.

2023-12-29 11:29 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalObject.java
> +public final class ConditionalObject<A> extends WithConditions<A> {
No because then each alternative would have alternatives

2023-12-29 11:32 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
> +                final var alt = ops.listBuilder();
I find it makes it more readable

2023-12-29 11:32 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
> +    public static final String ALTERNATIVES_KEY = "neoforge:alternatives";
Where would you put them? We can't have multiple root objects made out of thin air, they have to be somewhere.

2023-12-29 11:48 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalObject.java
> +public final class ConditionalObject<A> extends WithConditions<A> {
Ok then using the same type for the top-level and for entries is a mistake.

2023-12-29 11:50 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
> +                final var alt = ops.listBuilder();
It's just visual clutter everywhere. That doesn't add any value when writing the code nor when reading it

2023-12-29 11:53 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
> +    public static final String ALTERNATIVES_KEY = "neoforge:alternatives";
We need a documented spec of the order in which entries are processed at least. Personally I would do:
- Try to find first alternative that matches.
- If no match is found, check the top-level conditions.
- If the conditions match, return top level object. Else nothing.

2023-12-29 12:30 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalObject.java
> +public final class ConditionalObject<A> extends WithConditions<A> {
There can be no Codec for conditional objects if the with-alternatives and without-alternatives do not share a type.

2023-12-29 12:35 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalObject.java
> +public final class ConditionalObject<A> extends WithConditions<A> {
IMO all conditional codecs can be alternative-capable.

2023-12-29 12:38 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/common/conditions/ConditionalObject.java
> +public final class ConditionalObject<A> extends WithConditions<A> {
That's not the point, you can't decode an object *with* alternatives.

2024-07-04 21:26 UTC, sciwhiz12 commented
@Matyrobbrt, do you still intend on updating this PR to 1.21 and resolving the outstanding requested changes?

2024-07-05 20:51 UTC, Matyrobbrt commented
I don't plan to continue this PR for the foreseeable future, especially since the implementation is tricky in a generic fashion.

2024-07-05 20:51 UTC, closed without merging