Make chunk sections only be considered all air if filled with Blocks.AIR only
neoforged/NeoForge pull request #471
Opened 2024-01-06 15:07 UTC by TelepathicGrunt

A small PR to adjust how LevelChunkSection determines if it is entirely Air or not. 

## The problem this solves:

If you have a chunk section (16x16x16) filled with Cave Air to a modded block with isAir set to true, LevelChunkSection will return true for hasOnlyAir() which then will cause getBlockState to always return Blocks.AIR despite setting other air blocks in the chunk. This only happens when the entire chunk section is isAir true. Thus leading to confusion from players or modders who were so sure they placed a different air block in the chunk section before mining out the rest of it. It also makes it tougher for modders who has a modded isAir block with behavior and is supposed to fill a large area as now most of that will be converted automatically to Blocks.AIR. This PR aims to make the hasOnlyAir be true if the chunks ection is entirely Blocks.AIR and nothing else. This then would match the expected and resultant behavior being done in the game.

In the code, many of the LevelChunkSection hasOnlyAir calls keeps making the assumption that if that method is true, the spot must be Blocks.AIR. Multiple places makes this assumption. Not good for mods. Heck, not good for datapacks either that were trying to use CAVE_AIR or VOID_AIR as marker blocks.

## Why not replace LevelChunkSection's hasOnlyAir to be hasOnlyEmpy or isEmpty?

Would increase patch size significantly. Figured keeping it small would be more ideal.
![image](https://github.com/neoforged/NeoForge/assets/40846040/fc146d19-f23e-4afd-8547-0bf2e6c49f48)

## Why not add isEmpty to block and blockstate and check that in LevelChunkSection?

Realistically, this would be a useless method. If a modder made a block, then there's some behavior attached to the block or it is acting as some sort of marker. If we let modder mark it as isEmpty, suddenly, that block is replaced with isAir in certain chunk sections and the modder's goal with the block is lost. I cannot see any realistic purpose for marking a modded block as isEmpty and having it spontaneously turn into Blocks.AIR. Might as well just use Blocks.AIR in the first place.

## What performance impact will this have? Any changes to vanilla worldgen?

The only isAir blocks in vanilla are AIR, CAVE_AIR, and VOID_AIR:

- AIR is used everywhere. It's the main default block

- CAVE_AIR is used only in ravines, caves in Nether, and in underground structures/features such as Mineshafts, Dungeons, and Strongholds. Essentially none of these are placing CAVE_AIR in a large enough space to matter. Maybe a few very rare chunk sections in ravines might now retain their CAVE_AIR instead of converting to AIR. Performance impact? Practically none.

- VOID_AIR is used only for positions outside of the world's build limits. Essentially, it is only when outside the chunk's height ranges. In the case of the Nether, from y = 128 to y = 256, AIR is placed. Above y= 256, VOID_AIR is place.

Before change, what Nether roof has.
![image](https://github.com/neoforged/NeoForge/assets/40846040/485a7271-c208-4668-8cda-94df1fb77430)
![image](https://github.com/neoforged/NeoForge/assets/40846040/76a9345d-e840-46f9-9d9d-eab6df3b3344)

After change, what Nether roof has:
![image](https://github.com/neoforged/NeoForge/assets/40846040/7d988777-fc15-4d58-a93c-e6ed4af70c6e)

So even with this change, nothing changed with the Nether roof so no performance impact there in Nether and no change to vanilla behavior with the roof.

Hopefully this helps

2024-01-07 12:45 UTC, TelepathicGrunt commented
Closest Mojang issue report: https://bugs.mojang.com/browse/MC-232360

2024-01-07 13:55 UTC, marchermans requested changes, later dismissed

2024-01-07 13:55 UTC, marchermans commented on patches/net/minecraft/world/level/chunk/LevelChunkSection.java.patch
> ++        if (!blockstate.isEmpty()) { // NEO: Patched to make modded isAir blocks not be replaced with Blocks.AIR in all-air chunk sections
Please add the referenced Mojira issue number

2024-01-07 13:55 UTC, marchermans commented on patches/net/minecraft/world/level/chunk/LevelChunkSection.java.patch
> ++        if (!p_62995_.isEmpty()) { // NEO: Patched to make modded isAir blocks not be replaced with Blocks.AIR in all-air chunk sections
See above

2024-01-08 14:56 UTC, embeddedt commented
Your PR description is inconsistent. If `isEmpty` returns `true` for all three vanilla air blocks, then it behaves like `isAir` in a vanilla environment, so the patched code should behave identically to vanilla if there are no modded empty blocks. But then you say:

> Maybe a few very rare chunk sections in ravines might now retain their CAVE_AIR instead of converting to AIR. Performance impact? Practically none.

Could you clarify what you mean here?

2024-01-08 14:58 UTC, embeddedt requested changes
The same change should be made in `recalcBlockCounts`.

2024-01-08 15:05 UTC, TelepathicGrunt commented
> Your PR description is inconsistent. If `isEmpty` returns `true` for all three vanilla air blocks, then it behaves like `isAir` in a vanilla environment, so the patched code should behave identically to vanilla if there are no modded empty blocks. But then you say:
> 
> > Maybe a few very rare chunk sections in ravines might now retain their CAVE_AIR instead of converting to AIR. Performance impact? Practically none.
> 
> Could you clarify what you mean here?

Description was written before the suggestions in discord which was to preserve vanilla behavior so vanilla should see zero changes. Only impacts modded air blocks.

2024-01-08 21:13 UTC, embeddedt approved these changes
Seems fine. The call sites of `isEmpty` aren't super hot so I don't think any interface overhead is a concern.

2024-01-15 04:21 UTC, TheCurle approved these changes

2024-01-15 04:23 UTC, merged