Add system for conditional pack overlays
neoforged/NeoForge pull request #483
Opened 2024-01-10 21:44 UTC by lukebemish

The new pack overlay system allows resource or data packs to specify an "overlay" which is used to replace/add resources on certain pack format versions. This PR expands the overlay system with a "conditions" field, which allows mods to make *anything* conditional simply by placing it in a conditional pack overlay.

I implemented this by adding a "conditions" field to the overlay entry record; alternatively, I could have implemented this by instead making the list of overlays in the overlay metadata section use the conditional list codec - I avoided this because it makes datagen more painful.

2024-01-10 22:50 UTC, marchermans requested changes
Since 1.20.2 we use a conditional codec approach instead of holding on to the conditionals, please reimplement this using that architecture

2024-01-10 23:36 UTC, lukebemish commented
> Since 1.20.2 we use a conditional codec approach instead of holding on to the conditionals, please reimplement this using that architecture

Doing so requires substantial patches to all vanilla datagen around pack.mcmeta files or reimplementing it all on the forge end

2024-01-11 13:28 UTC, Technici4n approved these changes

2024-01-12 11:01 UTC, marchermans approved these changes

2024-01-12 11:03 UTC, merged