[1.20.4] Add Slime Split Event
neoforged/NeoForge pull request #524
Opened 2024-01-16 01:20 UTC by Shadows-of-Fire

This PR adds the `SlimeSplitEvent`, which is fired when a dying slime creates child slimes.  It provides access to the child and the parent to allow copying data, and can be cancelled to prevent the child from spawning.

Closes #521

2024-01-16 01:24 UTC, TheCurle approved these changes, later dismissed
Nice and simple.

2024-01-16 02:13 UTC, TelepathicGrunt commented
What about Magma Cubes?

2024-01-16 02:23 UTC, Shadows-of-Fire commented
`public class MagmaCube extends Slime`
Already handled :p

2024-01-16 02:25 UTC, TelepathicGrunt commented
Ah alright. The event name made it sound like it excluded Magma Cube. Not sure if there’s a better name to make it sound Ike it should be used for any entity that splits into more of themselves

2024-01-16 05:15 UTC, Shadows-of-Fire commented
Updated so that only one event is fired with access to all child slimes.

2024-01-16 05:51 UTC, Gaming32 commented
> Ah alright. The event name made it sound like it excluded Magma Cube. Not sure if there’s a better name to make it sound Ike it should be used for any entity that splits into more of themselves

I personally think of Magma Cubes as Nether slimes. They even used to be named Magma Slimes.

2024-01-16 06:16 UTC, Matyrobbrt requested changes

2024-01-16 06:16 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/event/entity/living/SlimeSplitEvent.java
> +     * Gets the mutable list of all child slimes.
You can use an inline return tag.

2024-01-16 06:16 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/event/entity/living/SlimeSplitEvent.java
> +     * Gets the parent slime that is in the process of being removed.
You can use an inline return tag.

2024-01-16 06:16 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/event/entity/living/SlimeSplitEvent.java
> +    protected boolean cancelled = false;
This field is useless?

2024-01-16 06:16 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/event/entity/living/SlimeSplitEvent.java
> +    public SlimeSplitEvent(Slime parent, List<Slime> children) {
Should be marked as `@Internal`

2024-01-16 10:12 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/event/entity/living/SlimeSplitEvent.java
> + * This event is fired whenever a slime is removed and splits into multiple child slimes.
I think it's worth adding that this fires for magma cubes and potentially other subclasses of Slime too.

2024-01-16 15:16 UTC, TelepathicGrunt commented
Copying my last comments from Discord to here:

The current event requires all entities that fire this event to extend Slime class which may not be true for modded slime mods that using their own class that doesn't extend Slime but still has the splitting behavior.

As long as the event’s type is Mob or LivingEntity instead of Slime, it tells people that the event could be firing for modded non-slime derived class and to do a check on the entity. That’s why the event name would be ideally renamed to maybe LivingEntitySplittingEvent. 

After all, we don’t have the issue of consumers of LivingEntityTickEvent not expecting it to be firing for all kinds of entities because the event name and typing already tells consumer it is broad and to do their own filtering inside.

2024-01-18 04:23 UTC, Shadows-of-Fire commented
Type bounds loosened to `Mob`.

2024-01-18 04:48 UTC, TelepathicGrunt approved these changes

2024-01-18 05:17 UTC, Matyrobbrt submitted a review, later dismissed

2024-01-18 05:17 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/event/entity/living/MobSplitEvent.java
> +     * {@return the mutable list of all children.}
Inline returns have no full stop at the end.

2024-01-18 05:17 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/event/entity/living/MobSplitEvent.java
> +     * {@return the parent mob, which is in the process of being removed.}
Inline returns have no full stop at the end.

2024-01-21 21:59 UTC, shartte approved these changes

2024-01-21 23:56 UTC, embeddedt approved these changes

2024-01-21 23:57 UTC, merged