[1.20.4] Fix inventoryTick and remove onArmorTick
neoforged/NeoForge pull request #549
Opened 2024-01-22 00:34 UTC by Shadows-of-Fire

This PR follows up on https://github.com/neoforged/NeoForge/pull/21 by removing the stale method `onArmorTick` and fixing the values of the parameters in `inventoryTick`.

Since there appears to be a lot of discussion on how best to solve the inventory tick problem, this is the minimal set of changes to restore current functionality to the best position.

I do believe that adding a more contextual version of `inventoryTick` with an arbitrary context object would benefit users in the long term, but that will need significant design work.

2024-01-22 13:41 UTC, Commoble approved these changes

2024-01-22 15:44 UTC, Technici4n requested changes

2024-01-22 15:44 UTC, Technici4n commented on patches/net/minecraft/world/entity/player/Inventory.java.patch
> ++                    // Neo: Fix the selected param to only be true for hotbar slots.
`this.selected` can only be between `0` and `9` so `this.selected == i` should already be correct.

2024-01-22 15:51 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
> -    default void onArmorTick(ItemStack stack, Level level, Player player) {}
I'm a bit hesitant on outright removing the method, I think it would be preferable to deprecate it for removal as we move towards a stable release.

2024-01-24 03:05 UTC, TheCurle commented on src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
> -    default void onArmorTick(ItemStack stack, Level level, Player player) {}
I second deprecating it for removal, this is too widely used to remove this late in the cycle IMHO.

2024-01-26 15:37 UTC, Technici4n commented
Please undo the `onArmorTick` removal so this can go in.

2024-01-28 23:35 UTC, Shadows-of-Fire commented
Updated to deprecate `onArmorTick` instead of removing it.

2024-01-29 18:23 UTC, Technici4n approved these changes

2024-01-29 21:31 UTC, merged