[1.20.4/5] Create BonusLootDropsEvent
neoforged/NeoForge pull request #625
Opened 2024-02-10 20:08 UTC by AnonymousHacker1279

Create a `BonusLootDropsEvent` which is fired before dropping items via the `ApplyBonusCount` loot function (for example, blocks with Fortune modifiers). It allows enchantment levels to be modified or a specific drop count to be set.

All of the variables/parameters available in `ApplyBonusCount.run()` are exposed through the event.

Example Usages:
```java
@SubscribeEvent
public static void bonusLootDropsEvent(BonusLootDropsEvent event) {
	// Add two extra enchantment levels when specific conditions are met
	if (event.getEntity() instanceof Player player) {
		if (playerMeetsSpecificConditions()) {
			event.setEnchantmentLevel(event.getEnchantmentLevel() + 2);
		}
	}
}
```
```java
@SubscribeEvent
public static void bonusLootDropsEvent(BonusLootDropsEvent event) {
	// Always set the drops to three when specific conditions are met
	if (event.getEntity() instanceof Player player) {
		if (playerMeetsSpecificConditions()) {
			event.setDropCount(3);
		}
	}
}
```

2024-02-10 20:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=625) <br/>All committers have signed the CLA.

2024-02-11 00:20 UTC, Shadows-of-Fire requested changes

2024-02-11 00:20 UTC, Shadows-of-Fire commented on patches/net/minecraft/world/level/storage/loot/functions/ApplyBonusCount.java.patch
> ++    public interface Formula {
should be an AT

2024-02-11 00:20 UTC, Shadows-of-Fire commented on patches/net/minecraft/world/level/storage/loot/functions/ApplyBonusCount.java.patch
> ++    public static record FormulaType(ResourceLocation id, Codec<? extends ApplyBonusCount.Formula> codec) {
should be an AT

2024-02-11 00:21 UTC, Shadows-of-Fire commented
Not 100% convinced this is a great solution, especially because changing the enchantment level is totally superseded by someone else modifying the drop count.

2024-02-11 00:38 UTC, AnonymousHacker1279 commented on patches/net/minecraft/world/level/storage/loot/functions/ApplyBonusCount.java.patch
> ++    public interface Formula {
AT added in latest commit

2024-02-11 00:38 UTC, AnonymousHacker1279 commented on patches/net/minecraft/world/level/storage/loot/functions/ApplyBonusCount.java.patch
> ++    public static record FormulaType(ResourceLocation id, Codec<? extends ApplyBonusCount.Formula> codec) {
AT added in latest commit

2024-02-11 00:40 UTC, AnonymousHacker1279 commented
The drop count method intentionally acts as a final say-so in case a mod decides it needs to force it for any reason. I can change this if desired though.

2024-02-25 09:55 UTC, marchermans requested changes
I am not going to review this further.
This PR has had a merge failure at some point and I suggest starting a new with a fresh branch and then force pushing to your old branch to get it back into a working state.

Turning this PR into a draft.

2024-02-25 09:55 UTC, marchermans commented on build.gradle
> -    from '20.4'
No, obviously this was not checked!

2024-02-25 09:55 UTC, marchermans commented on patches/com/mojang/blaze3d/vertex/VertexFormatElement.java.patch
> - }
Your merge completely failed!

2024-02-25 17:43 UTC, AnonymousHacker1279 commented
My apologies, I did not catch the merge failure when updating my branch through GitHub Desktop. I have force-pushed this branch from a fresh one.

2024-02-27 14:43 UTC, marchermans commented
Okey that merge disaster is indeed fixed, now to the content.

Would a GLM not work here?

2024-02-27 15:01 UTC, AnonymousHacker1279 commented
The problems with GLMs for this particular use scenario is that they run *after* loot is generated, and Fortune-style modifiers run before.

There was a [more extended discussion](https://discord.com/channels/313125603924639766/852298000042164244/1205968935498022962) on Discord regarding this.

2024-02-27 19:08 UTC, KnightMiner commented
In the past, the forge recommendation for how to deal with this issue is to use a GLM to delete all generated loot then create a modified context to rerun the loot table. Obviously this is a horrible solution as it means other GLMs trying a similar approach are clobbered, but this is why this has never been addressed.

Not sure if the silk touch GLM doing that is still around, that case at least is long since handled by item enchantment overrides.

2024-02-27 19:51 UTC, AnonymousHacker1279 commented
I was referred to the `GetEnchantmentLevelEvent` introduced in #503 however my particular use case was being able to adjust Fortune levels based on an armor set bonus, meaning I needed a player context of some sort. It was mentioned in Discord that ideally the `GetEnchantmentLevelEvent` would contain this context, but the patch surface was too high to be feasible. 

Later this evening I can improve the JavaDocs on this event to explain when it should be used over the other event.

2024-07-04 10:45 UTC, sciwhiz12 commented
Hello! Do you intend to continue with this PR? If so, please fix the merge conflicts.

2024-07-05 17:11 UTC, AnonymousHacker1279 commented
I have no intentions of continuing the PR at this point.

2024-07-05 17:11 UTC, closed without merging