[1.20.5] Remove `CommonHooks#getBurnTime` and move contents to `ItemStack#getBurnTime`
neoforged/NeoForge pull request #633
Opened 2024-02-13 12:27 UTC by Spinoscythe

Fixes #632

2024-02-13 14:22 UTC, Technici4n requested changes
This will be for 1.20.5.

2024-02-13 14:22 UTC, Technici4n commented on patches/net/minecraft/world/item/ItemStack.java.patch
> ++    public int getBurnTime(@org.jetbrains.annotations.Nullable net.minecraft.world.item.crafting.RecipeType<?> recipeType) {
The body should be in `IItemStackExtension`.

2024-02-13 14:28 UTC, Spinoscythe commented on patches/net/minecraft/world/item/ItemStack.java.patch
> ++    public int getBurnTime(@org.jetbrains.annotations.Nullable net.minecraft.world.item.crafting.RecipeType<?> recipeType) {
@Technici4n Correct me if I'm wrong, but shouldn't this be implemented in `Item` via `IItemExtension`? because the `ItemStack`'s burn time should be the `Item`'s burn time

2024-02-13 14:52 UTC, Technici4n commented on patches/net/minecraft/world/item/ItemStack.java.patch
> ++    public int getBurnTime(@org.jetbrains.annotations.Nullable net.minecraft.world.item.crafting.RecipeType<?> recipeType) {
The `ItemStack` function can perform extra logic. The `Item` method is only for overrides, not for queries.

2024-02-14 11:00 UTC, marchermans approved these changes, later dismissed

2024-02-16 23:37 UTC, pupnewfster commented on src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
> +        var fuel = self().getItemHolder().getData(NeoForgeDataMaps.FURNACE_FUELS);
Shouldn't this still be checking if the burn time is overridden on the item to allow for nbt sensitive fuels?

2024-02-19 15:55 UTC, pupnewfster approved these changes

2024-03-10 19:42 UTC, closed without merging