Address UseItemOnBlockEvent player nullability by fixing event inheritance
neoforged/NeoForge pull request #669
Opened 2024-02-28 10:29 UTC by Technici4n

The breakage has been minimized by reimplementing every method from the previous parents. If mods were casting the event to one of its superclasses, then the breakage cannot be avoided.

Fixes #661.

2024-02-28 11:21 UTC, Matyrobbrt requested changes
Given that this is a breaking change and that the events are going to need these changes in 1.20.5 anyway, I would rather use a fake player for nulls until then.

The more alternative alternative here is also not fixing the event until 1.20.5 which I also find acceptable.

2024-02-28 12:02 UTC, Technici4n commented
> The more alternative alternative here is also not fixing the event until 1.20.5 which I also find acceptable.

Or potentially we only fire the event if there is a non-null player.

2024-02-29 12:54 UTC, marchermans commented
> Given that this is a breaking change and that the events are going to need these changes in 1.20.5 anyway, I would rather use a fake player for nulls until then.
> 
> The more alternative alternative here is also not fixing the event until 1.20.5 which I also find acceptable.

From internal discussions with other maintainers: Several of us do not find the FakePlayer solution acceptable at all. It bastardizes the use of FakePlayers since 99% of the required context to create one is missing!

As such I we also proposed to simply not fix it. Or remove the annotation. We never indicated that we are 100% binary compatible with Kotlin, au contraire we have often completed stated that kotlin is not **officially** supported, and that other languages are only a second tier consideration. So in reality we could just remove the violating annotation without really a problem. But I guess that does not change the problem. The player is still null.

2024-02-29 13:13 UTC, Technici4n commented
Closing as #670 was merged.

2024-02-29 13:13 UTC, closed without merging