[1.20.4] Expand model-level AO hook to allow force-enabling AO irrespective of a block's light emission
neoforged/NeoForge pull request #719
Opened 2024-03-16 16:43 UTC by XFactHD

This PR expands the `BakedModel` AO hook to allow custom models to override the AO behavior in both directions instead of only being able to force-disable AO. If smooth lighting is enabled in the video settings, then the default vanilla behavior is to render a model with AO unless the model opts out or the block emits any light. This behavior may in certain cases not be desired though and the expanded hook allows overriding it in those cases.
The global smooth lighting video setting cannot be overruled by this hook, it has final say whether AO is available or not.

Replicating this enhanced AO control on the per-quad AO hook would be desirable as well, but would require significantly more extensive changes and is therefore better left to a separate PR, if not even part of a more thorough rework of the model hooks.

My use case is to force-enable AO on light-emitting fake blocks to prevent the light emission breaking the illusion of the fake block. The screenshots below show the difference between the status-quo and force-enabling AO on light-emitting blocks:
<img src="https://github.com/neoforged/NeoForge/assets/11262040/cf89245f-fc81-421a-beff-908ddf783f68" width="50%"><img src="https://github.com/neoforged/NeoForge/assets/11262040/925313f4-4625-4880-a472-75db3934efee" width="50%">
The effect becomes significantly more obvious when shaders are in play as well (screenshots made in 1.20.1):
<img src="https://github.com/neoforged/NeoForge/assets/11262040/41277aae-1412-4fd1-8170-8b154378cbba" width="50%"><img src="https://github.com/neoforged/NeoForge/assets/11262040/ff8373ea-b159-4d01-862b-eceb84c90e9b" width="50%">

2024-03-16 19:07 UTC, embeddedt approved these changes, later dismissed

2024-03-18 10:45 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/util/TriState.java
> +public enum TriState {
Yes please! Can you add some javadoc to the class itself and its values?

2024-03-18 10:47 UTC, Technici4n requested changes
Good idea.

The MultiPart and Weighted overrides are very crude, but whatever. That can only be solved with a full FRAPI-style redesign of `BakedModel`.

2024-03-18 10:47 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/client/extensions/IBakedModelExtension.java
> +    @Deprecated(forRemoval = true)
Please add `since` to the deprecation.

2024-03-18 22:32 UTC, Technici4n approved these changes

2024-03-18 22:36 UTC, merged