Add sprite getter to FluidSpriteCache
neoforged/NeoForge pull request #747
Opened 2024-03-26 00:42 UTC by TelepathicGrunt

Allows modders to use the sprite cache in their renderFluid method within IClientFluidTypeExtensions. Allows modders to not need to maintain their own texture cache and a resourcelistener to bust that cache. Instead, allow Neoforge to handle all that for them.

2024-03-26 01:11 UTC, embeddedt requested changes

2024-03-26 01:11 UTC, embeddedt commented on src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java
> +    public static TextureAtlasSprite getSprites(ResourceLocation texture) {
Should be `getSprite` since it's returning one.

2024-03-26 01:19 UTC, XFactHD approved these changes, later dismissed

2024-03-26 01:20 UTC, embeddedt approved these changes, later dismissed

2024-03-26 13:39 UTC, Technici4n submitted a review, later dismissed

2024-03-26 13:40 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java
> +     * {@return a specified sprite or a missing sprite texture if sprite is not found.
You forgot the closing `}`, and the final `.` is not needed (it's already added by `{@return }`).

2024-03-27 00:43 UTC, XFactHD approved these changes

2024-03-27 08:14 UTC, merged