Adds a registryDump command
neoforged/NeoForge pull request #786
Opened 2024-04-06 02:40 UTC by TelepathicGrunt

This adds a very useful command that can dump the entries of any registry into a file. 
`/neoforge registryDump <registry> <alphabeticalSort> <printNumericIds>`

The command has ability to autocomplete a registry name and display what is selectable. Works with worldgen registries as well. The options available are if to sort entries alphabetically or print numeric ids. If numeric id is true and alphabetical is false, the file will be sorted by the numeric id automatically. 

The output of the command says what registry it was using and adds a clickable link that will open the file automatically for you.

Location of the file is put into the `registry_dumps` folder in the game directory (next to the configs and mods folder)

Images of how command looks and file outputs:
![image](https://github.com/neoforged/NeoForge/assets/40846040/20bee1cd-7986-41c7-a55e-433dd117c4e9)

![image](https://github.com/neoforged/NeoForge/assets/40846040/ab6ae280-aec0-4205-be5e-dbd71dc1ce15)
![image](https://github.com/neoforged/NeoForge/assets/40846040/179a9c96-a0cf-4de6-a314-fe1b201b43e5)
![image](https://github.com/neoforged/NeoForge/assets/40846040/f73242c9-6de3-4a9d-9d3f-0e826524fdc9)

![image](https://github.com/neoforged/NeoForge/assets/40846040/f226924f-0c15-48d1-8f34-980a34f9f3a5)
![image](https://github.com/neoforged/NeoForge/assets/40846040/d09f0502-d39b-4e62-99c6-86ecc1773a9b)

![image](https://github.com/neoforged/NeoForge/assets/40846040/6c2e223f-f4b9-4404-9a7f-b2ec0cd9d28f)
![image](https://github.com/neoforged/NeoForge/assets/40846040/d364ad4e-c38b-45f0-95f6-e315c4831118)

![image](https://github.com/neoforged/NeoForge/assets/40846040/044090ad-0220-455d-a5b2-32304678ce52)
![image](https://github.com/neoforged/NeoForge/assets/40846040/713b8225-5111-43c4-b68a-60b4c49207ea)

Closes: https://github.com/neoforged/NeoForge/issues/7821

2024-04-06 03:28 UTC, Shadows-of-Fire commented
I would suggest sending the output files to folders by namespace, transforming `minecraft_entity_type.txt` to `minecraft/entity_type.txt`

2024-04-06 03:49 UTC, TelepathicGrunt commented
![image](https://github.com/neoforged/NeoForge/assets/40846040/ac5b2d38-386e-4100-82f5-b4d7769f3a45)
![image](https://github.com/neoforged/NeoForge/assets/40846040/69e6efe1-564d-4862-8402-aa520610fd42)
![image](https://github.com/neoforged/NeoForge/assets/40846040/ed04f932-0864-4356-8575-b209a0b5d2d3)

2024-04-06 04:01 UTC, TelepathicGrunt commented
Command is now `/neoforge dump registry <registry> <alphabetical_sort> <print_numeric_ids>` and will print to the game directory's `dumps/registry` folder. The registry's namespace is now a folder inside. And command is now level three `Commands.LEVEL_ADMINS`

2024-04-11 16:07 UTC, Matyrobbrt requested changes

2024-04-11 16:07 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/server/command/CommandUtils.java
> +        return (ctx, builder) -> CommandUtils.getResourceKey(ctx, "registry", registryKey)
The registry argument name should be configurable.

2024-04-11 16:07 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/server/command/DumpCommand.java
> +            Path registryDumpFile = Paths.get(registryNamespaceDirectory.toString(), fileName);
```suggestion
            Path registryDumpFile = registryNamespaceDirectory.resolve(fileName);
```

2024-04-11 16:07 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/server/command/DumpCommand.java
> +                    outputStream.write((results + "\r\n").getBytes());
No need for a carriage return.

2024-04-11 16:07 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/server/command/DumpCommand.java
> +            return 1;
You should return `Command#SINGLE_SUCCESS` instead.

2024-04-12 09:05 UTC, Matyrobbrt requested changes

2024-04-12 09:05 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoforge/server/command/DumpCommand.java
> + * </ul>
Useless unopened tag

2024-04-12 19:30 UTC, Matyrobbrt commented on src/main/resources/assets/neoforge/lang/en_us.json
> +  "commands.neoforge.dump.error.unknown_element": "Unknown element '%s' in registry '%s'",
This is unused? And `commands.neoforge.dump.error.unknown_registry` is not defined.

2024-04-12 19:34 UTC, TelepathicGrunt commented on src/main/resources/assets/neoforge/lang/en_us.json
> +  "commands.neoforge.dump.error.unknown_element": "Unknown element '%s' in registry '%s'",
Dump success is used here:
https://github.com/neoforged/NeoForge/pull/786/files#diff-658549d4e44224881b02ffc547977fbfaff33f49931bc0f0ec41d44221f14fd2R100

Dump failure is used here:
https://github.com/neoforged/NeoForge/pull/786/files#diff-658549d4e44224881b02ffc547977fbfaff33f49931bc0f0ec41d44221f14fd2R110

And unknown registry is used here:
https://github.com/neoforged/NeoForge/pull/786/files#diff-658549d4e44224881b02ffc547977fbfaff33f49931bc0f0ec41d44221f14fd2R66

2024-04-12 19:35 UTC, TelepathicGrunt commented on src/main/resources/assets/neoforge/lang/en_us.json
> +  "commands.neoforge.dump.error.unknown_element": "Unknown element '%s' in registry '%s'",
Err typo on last one. Will fix

2024-04-12 19:36 UTC, TelepathicGrunt commented on src/main/resources/assets/neoforge/lang/en_us.json
> +  "commands.neoforge.dump.error.unknown_element": "Unknown element '%s' in registry '%s'",
unknown_registry is fixed to match the lang key in the java file

2024-04-13 07:09 UTC, Matyrobbrt commented on src/main/resources/assets/neoforge/lang/en_us.json
> +  "commands.neoforge.dump.error.unknown_registry": "Unknown element '%s' in registry '%s'",
```suggestion
  "commands.neoforge.dump.error.unknown_registry": "Unknown registry '%s'",
```

2024-04-13 07:10 UTC, Matyrobbrt approved these changes

2024-04-13 07:16 UTC, merged