First docs for porting
neoforged/NeoForge pull request #805
Opened 2024-04-15 20:39 UTC by shartte

2024-04-25 16:57 UTC, Minecraftschurli commented on docs/CONTRIBUTING.md
> +
idk if the contributing file is the right place for this since it is a maintainer exclusive thing to do

2024-04-29 16:19 UTC, shartte commented on docs/CONTRIBUTING.md
> +
Split into PORTING.md

2024-04-29 16:50 UTC, Minecraftschurli requested changes

2024-04-29 16:50 UTC, Minecraftschurli commented on docs/PORTING.md
> +   2. Fill out the survey
survey -> fields

2024-04-29 16:50 UTC, Minecraftschurli commented on docs/PORTING.md
> +10. Apply formatting (`applyAllFormatting`)
create squash branch after generating the patches

2024-04-29 16:50 UTC, Minecraftschurli commented on docs/PORTING.md
> +12. Squash all commits from "Initial base" created by the action, ensure the resulting commit contains no bot authorship (due to CLA signing issues later).
bot authorship is irrelevant now

2024-04-29 19:12 UTC, Matyrobbrt commented on docs/PORTING.md
> +12. Squash all commits from "Initial base" created by the action, ensure the resulting commit contains no bot authorship (due to CLA signing issues later).
It is still useless noise, the bot has no reason to be in the commits.

2024-04-29 19:43 UTC, shartte commented on docs/PORTING.md
> +12. Squash all commits from "Initial base" created by the action, ensure the resulting commit contains no bot authorship (due to CLA signing issues later).
yeah, I'd like to keep this.

2024-04-29 20:08 UTC, shartte commented on docs/PORTING.md
> +10. Apply formatting (`applyAllFormatting`)
Addressed

2024-04-29 20:09 UTC, shartte commented on docs/PORTING.md
> +   2. Fill out the survey
Addressed

2024-05-04 12:04 UTC, Minecraftschurli approved these changes

2024-05-04 19:23 UTC, merged