[1.20.5] Patch in `MutableDataComponentHolder` interface (Updates for #817)
neoforged/NeoForge pull request #821
Opened 2024-04-18 17:31 UTC by ApexModder

Copy of #817 with requested code changes

--- 

> Patches in mutable DataComponentHolder interface to allow instance checking for mutability, vanilla interface only allows for immutable lookups.
> 
> This new interface is implemented onto ItemStack and FluidStack and comes with a handy copyInto method to easily copy components from 1 holder into another.
> 
> Update: This pr includes all changes from https://github.com/neoforged/NeoForge/pull/816

2024-04-18 17:42 UTC, shartte approved these changes

2024-04-18 17:51 UTC, Technici4n requested changes

2024-04-18 17:51 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/MutableDataComponentHolder.java
> +    default <T> void copyFrom(DataComponentHolder src, DataComponentType<T> componentType) {
I have a slight preference for the first argument being the `DataComponentType`, for consistency with the other methods.

2024-04-18 20:42 UTC, Technici4n approved these changes

2024-04-19 00:58 UTC, ApexModder commented
Added a couple more supplier methods in places where they were missing

I also noticed that when copying the mutating methods from `ItemStack` into `MutableDataComponentHolder` I missed the `applyComponents` methods, would it make sense to copy these over too or should those remain specific to the stack classes?

2024-04-19 18:06 UTC, Technici4n requested changes
I think that this is too much. We're adding a lot of code just to save a few `.get()` calls.

2024-04-19 18:52 UTC, Technici4n commented on src/main/java/net/neoforged/neoforge/common/extensions/IDataComponentMapBuilderExtensions.java
> +import javax.annotation.Nullable;
We generally use the jetbrains one.

2024-04-19 18:54 UTC, ApexModder commented on src/main/java/net/neoforged/neoforge/common/extensions/IDataComponentMapBuilderExtensions.java
> +import javax.annotation.Nullable;
Whoops, so do I usually, guess idea auto filled javax for what ever reason

2024-04-19 18:56 UTC, Technici4n approved these changes

2024-04-19 19:27 UTC, merged