[1.20.1] Deprecate the `TagKey` constructor
neoforged/NeoForge pull request #854
Opened 2024-04-24 19:57 UTC by ctrlaltmilk

The `TagKey` constructor does not intern the value correctly, and therefore should be avoided. Unfortunately, as `TagKey` is a record, we can't make the constructor private. The best solution seems to deprecate the constructor, with a link to `TagKey#create` instead.

2024-04-24 20:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=854) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/neoforged/NeoForge?pullRequest=854) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neoforged/NeoForge?pullRequest=854) it.</sub>

2024-04-24 20:23 UTC, Technici4n commented
Interestingly this is already the case in 1.20.5 in vanilla minecraft.

2024-04-25 18:43 UTC, Technici4n requested changes
Just one nitpick.

2024-04-25 18:43 UTC, Technici4n commented on patches/minecraft/net/minecraft/tags/TagKey.java.patch
> ++    * @deprecated Forge: Use {@link TagKey#create} instead.
Our prefix is `Neo:`, please change `Forge:` to that.

2024-04-25 21:37 UTC, ctrlaltmilk commented on patches/minecraft/net/minecraft/tags/TagKey.java.patch
> ++    * @deprecated Forge: Use {@link TagKey#create} instead.
ooh got it, just fixed

2024-04-25 21:57 UTC, Technici4n approved these changes

2024-04-26 00:33 UTC, embeddedt approved these changes
Can't hurt

2024-04-26 00:33 UTC, merged