Fixed #85
neoforged/NeoForge pull request #93
Opened 2023-08-08 12:35 UTC by Icosider

2023-08-08 12:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/neoforged/NeoForge?pullRequest=93) <br/>All committers have signed the CLA.

2023-08-08 13:22 UTC, sciwhiz12 requested changes

2023-08-08 13:22 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +        }, Util.ioPool());
I believe the background executor would be more appropriate here, as the IO pool should be reserved only for IO tasks.

2023-08-08 13:25 UTC, sciwhiz12 commented
I will also note that we need to properly document `ServerChatEvent` as being fired _not_ on the main game thread, but on a separate thread (such as the background executor). Currently, it is not documented as such, which may cause issues if listeners try to read or affect the game state from a thread other than the main game thread.

2023-08-08 13:43 UTC, Icosider commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +        }, Util.ioPool());
Yes, that's right, you say, I used this executor for an example. I need to discuss a more correct approach with someone, since Minecraft itself has a ready-made thread-pool, or it's worth creating your own to handle chat formatting. And I also relied on the code of Minecraft itself, which formatting produces through I/O threads. At least that was the case on 1.19.2

2023-08-08 13:44 UTC, Icosider commented
> I will also note that we need to properly document `ServerChatEvent` as being fired _not_ on the main game thread, but on a separate thread (such as the background executor). Currently, it is not documented as such, which may cause issues if listeners try to read or affect the game state from a thread other than the main game thread.

Do you need JavaDoc for this event or do I need more detailed information in the code itself?

2023-12-20 21:46 UTC, embeddedt commented
This PR hasn't been worked on in a long time and is out of sync with the `1.20.x` branch. Please make a new PR if you're still interested in fixing this.

2023-12-20 21:46 UTC, closed without merging