Replace PlantType system with SpecialPlantable interface and canSustainPlant block method
neoforged/NeoForge pull request #971
Opened 2024-05-17 22:09 UTC by TelepathicGrunt

It is well known the old PlantType system used in past is quite clunky and broken in many areas. It does not even cover some important vanilla plants such as Cocoa.

Basically, it tried to be many things at once and failed at all of them. It tried to allow for blocks to define what plant it can keep as well as control what modded crops villagers can place.

This PR splits the two goals into separate systems.

1. SpecialPlantable interface (any suggestions of different name?)

    - This replaces the `IPlantable` interface and instead of being on blocks, you would put the SpecialPlantable interface on your own custom item classes. 
    - The interface will force you to define `canPlacePlantAtSpot` and `spawnPlantAtSpot` methods.
    - Other mods will instanceof check for the interface on an item and if present, will call these two methods to check if the item can place a plant at a spot and if so, call the other method to spawn the plant. This allows for the item to spawn larger or more complex plants through mod interactions instead of just a normal BlockItem.
    - Vanilla items are untouched as they are BlockItems. Mods can still find those crop items by checking if in ItemTags.VILLAGER_PLANTABLE_SEEDS tag and then call the BlockItem's method for placing the crop. Again, the interface is for crops that are more complex than a BlockItem.
    - Thoughts? Any way to improve this interface? Or is it not a good idea?
    
2. Changed canSustainPlant to return a Tristate and patched it into more blocks

   - Modded soil blocks will override `canSustainPlant` and return TRUE, FALSE, or DEFAULT enum. If DEFAULT, the plant block will continue to run it's normal logic for checking survivability. If TRUE or FALSE is returned, it will override the plant's survivability checks to what the soil block wants.
   - Modded plant blocks that override `canSurvive` method should call `canSustainPlant` on the block the plant is attaching to and respect the enum result that comes out. Basically, modded plants will have to "opt-in" into this system. If the pklant overrides `mayPlace` method, they will still respect `canSustainPlant` because the patches tries to target the `canSurvive` methods where-ever it makes sense
   - The patches to the vanilla blocks to support `canSustainPlant` are in places where vanilla is doing block type checks or light checks. Any check for block shape was ignored to keep patch size down and because those kinds of plants technically support any block as long as the block's shape is good for supporting the plant.
   - `CropBlock`'s `getGrowthSpeed` method had its first parameter changed from `Block` to `BlockState`in order to pass in the correct crop block's blockstate to  `canSustainPlant`. No idea why mojang passed only the Block in but this is an annoying breaking change to a vanilla method param type I ended up doing. Any suggestions around this?
   - Support far more vanilla blocks than the old PlantType system did. It includes Cocoa, Chorus Plant, and more! Let me know if there's any specific plant that needs the hook.

3. Added GameTests for all kinds of plants

   - I added gametests for each kind of plant to make sure there's no regression on logic in future and catch missed patches much easier.
   - Note: I was not able to make gametest that test the plant's survivability in the dark because the lighting engine is too problematic to handle during gametests. Darkness survivability checking will have to be done manually for Red/Brown mushroom blocks on non-myclium and making sure crops cannot be planted in the dark.
   
Feed back welcomed as there's a lot of improvements that can be done to this PR.

2024-05-17 22:30 UTC, Spinoscythe commented
@TelepathicGrunt `canPlacePlantAtSpot` -> `canPlacePlantAtPosition` maybe?

2024-05-17 22:53 UTC, Spinoscythe commented
`SpecialPlantable` -> `BasePlantable`?

2024-05-18 18:48 UTC, FiniteReality commented on src/main/java/net/neoforged/neoforge/common/SpecialPlantable.java
> +    default boolean villagerCanPlantItem() {
Maybe it's worth passing the villager to villagerCanPlantItem, so that certain plants can only be plantable by certain villagers?

2024-05-19 01:01 UTC, XFactHD requested changes

2024-05-19 01:01 UTC, XFactHD commented on patches/net/minecraft/world/level/block/BambooSaplingBlock.java.patch
> ++        return soilDecision == net.neoforged.neoforge.common.util.TriState.DEFAULT ? p_48987_.getBlockState(p_48988_.below()).is(BlockTags.BAMBOO_PLANTABLE_ON) : soilDecision == net.neoforged.neofor
If you invert the `soilDecision == TriState.DEFAULT` check and replace the ternary with an if statement, you can avoid copying the original check.

2024-05-19 01:01 UTC, XFactHD commented on patches/net/minecraft/world/level/block/BambooStalkBlock.java.patch
> ++        return soilDecision == net.neoforged.neoforge.common.util.TriState.DEFAULT ? p_262154_.getBlockState(p_261493_.below()).is(BlockTags.BAMBOO_PLANTABLE_ON) : soilDecision == net.neoforged.neof
See point about inversion above

2024-05-19 01:01 UTC, XFactHD commented on patches/net/minecraft/world/level/block/BushBlock.java.patch
> ++        return soilDecision == net.neoforged.neoforge.common.util.TriState.DEFAULT ? this.mayPlaceOn(belowBlockState, p_51029_, blockpos) : soilDecision == net.neoforged.neoforge.common.util.TriStat
See point about inversion above

2024-05-19 01:01 UTC, XFactHD commented on patches/net/minecraft/world/level/block/CactusBlock.java.patch
> ++        return soilDecision == net.neoforged.neoforge.common.util.TriState.DEFAULT ? ((blockstate1.is(Blocks.CACTUS) || blockstate1.is(BlockTags.SAND)) && !p_51154_.getBlockState(p_51155_.above()).l
See point about inversion above

2024-05-19 01:01 UTC, XFactHD commented on patches/net/minecraft/world/level/block/CocoaBlock.java.patch
> ++        return soilDecision == net.neoforged.neoforge.common.util.TriState.DEFAULT ? blockstate.is(BlockTags.JUNGLE_LOGS) : soilDecision == net.neoforged.neoforge.common.util.TriState.TRUE;
See point about inversion above

2024-05-19 01:01 UTC, XFactHD commented on patches/net/minecraft/world/level/block/CropBlock.java.patch
> ++        return soilDecision == net.neoforged.neoforge.common.util.TriState.DEFAULT ? hasSufficientLight(p_52283_, p_52284_) && super.canSurvive(p_52282_, p_52283_, p_52284_) : soilDecision == net.ne
See point about inversion above

2024-05-19 01:01 UTC, XFactHD commented on patches/net/minecraft/world/level/block/SmallDripleafBlock.java.patch
> ++            return soilDecision == net.neoforged.neoforge.common.util.TriState.DEFAULT ? this.mayPlaceOn(blockstate, p_154616_, blockpos) : soilDecision == net.neoforged.neoforge.common.util.TriStat
See point about inversion above

2024-05-19 01:53 UTC, TelepathicGrunt commented
> @TelepathicGrunt `SpecialPlantable` -> `BasePlantable`?

BasePlantable sounds like it is for vanilla plantable items too. But the interface is better suited for special plantable blocks that aren't simple villager plantable tagged BlockItems.

2024-06-06 01:44 UTC, XFactHD requested changes
Please double-check all positions and directions passed to `canSustainPlant()`. In my testing I noticed that at least two cases had one of them wrong.

2024-06-06 01:44 UTC, XFactHD commented on patches/net/minecraft/world/level/block/CocoaBlock.java.patch
> ++        net.neoforged.neoforge.common.util.TriState soilDecision = blockstate.canSustainPlant(p_51768_, p_51769_.relative(p_51767_.getValue(FACING)), p_51767_.getValue(FACING), p_51767_);
The direction passed in must be facing away from the soil block
```suggestion
+        net.neoforged.neoforge.common.util.TriState soilDecision = blockstate.canSustainPlant(p_51768_, p_51769_.relative(p_51767_.getValue(FACING)), p_51767_.getValue(FACING).getOpposite(), p_51767_);
```

2024-06-06 01:44 UTC, XFactHD commented on patches/net/minecraft/world/level/block/ChorusPlantBlock.java.patch
> ++        net.neoforged.neoforge.common.util.TriState soilDecision = blockstate.canSustainPlant(p_51725_, p_51726_, Direction.UP, p_51724_);
The position passed in must be the soil's position, not the plant's position.
```suggestion
+        net.neoforged.neoforge.common.util.TriState soilDecision = blockstate.canSustainPlant(p_51725_, p_51726_.below(), Direction.UP, p_51724_);
```

2024-06-07 00:38 UTC, XFactHD approved these changes, later dismissed
The implementation looks fine to me now.

Mods adding blocks which pretend to be something else and therefore needing to check whether the block they are pretending to be can sustain a given plant will take a hit from this, but there is no satisfactory solution at the moment which provides this ability to such mods while still providing plants the ability to check basically whatever they want in their survivability checks (the status-quo fails on the latter part).

Ideally I'd like a second opinion from someone how uses this API from the plant side, but I cannot think of anyone off the top of my head.

2024-06-08 17:20 UTC, Ketheroth commented
I have a question about villagers planting `SpecialPlantable` crops. The current `HarvestFarmland` patch only allows `SpecialPlantable` crops to grow on farmland. However, mods (like the one I dev, agricraft) that have crops growing on non-farmland blocks can't have these crops grown by a villager. Would it be possible to move that patch outside the check `if (block instanceof FarmBlock)` to allow villagers to plant this kind of plants? (an example would be a crop growing on podzol)

Is it also possible to add the itemstack of the to be planted item in the methods of `SpecialPlantable` to allow nbt/component checks by the implementer?

2024-06-08 18:09 UTC, TelepathicGrunt commented
@Ketheroth Instead of moving the SpecialPlantable check, I added `neoforge:villager_farmlands` block tag instead to replace the two instanceof FarmBlock checks. Moving the SpecialPlantable check would had done nothing because Villagers check first if the block they want to pathfind to is a FarmBlock so they would not had pathfinded to Podzol at all. Now with the new tag, they will.

Does mean any mod relying of extending FarmBlock need to add to this tag now to recover their previous behavior

2024-06-22 13:40 UTC, XFactHD submitted a review, later dismissed

2024-06-24 00:14 UTC, XFactHD submitted a review, later dismissed
I would still like a second pair of eyes on this

2024-06-26 13:26 UTC, pupnewfster requested changes

2024-06-26 13:26 UTC, pupnewfster commented on patches/net/minecraft/world/level/block/CropBlock.java.patch
> ++    protected static float getGrowthSpeed(BlockState p_52273_, BlockGetter p_52274_, BlockPos p_52275_) {
We if we don't change the parameter type and instead add one, or instead change the name of the Block -> BlockState parameter, and then on the next line do `Block p_52273_ = state.getBlock()` then I think it will reduce how much of this method has to be patched just to be adding extra `.getBlock()` calls

2024-06-26 13:26 UTC, pupnewfster commented on patches/net/minecraft/world/level/block/ChorusFlowerBlock.java.patch
> ++                else if (blockstate.is(Blocks.END_STONE)) {
If you move this `else` onto its own line:
```java
else
if (blockstate.is(Blocks.END_STONE)) {
```
Then this hunk won't have to be removing a line

2024-06-26 22:18 UTC, pupnewfster approved these changes, later dismissed

2024-06-26 22:35 UTC, pupnewfster approved these changes

2024-06-26 22:42 UTC, merged