Fix chunk future chain not being bypassed for entity loads in 1.17+
neoforged/NeoForge pull request #99
Opened 2023-08-13 20:05 UTC by embeddedt

The chunk future bypass added in https://github.com/MinecraftForge/MinecraftForge/pull/7697 no longer functions completely since 1.17. In 1.16 entities were added within the try/finally block, but in 1.18 (and thus presumably 1.17) entity adding is now done inside `levelChunk.runPostLoad`, which runs before that block.

This PR adapts to the vanilla change by adding a second wrapper around `runPostLoad`.

This should hopefully fix some widespread issues with mods using `EntityJoinLevelEvent` causing deadlocks.

2023-08-13 22:46 UTC, TheCurle commented
I'd appreciate if you change the Forge - comment lines to be Neo:

We haven't yet got a finalised contributors guide, so this may not be a common request, I just figured it's worth asking.

2023-08-13 23:05 UTC, pupnewfster commented
For reference they would be changed from `// Forge - <message>` to `// Neo: <message>`

2023-08-14 01:08 UTC, embeddedt commented
Do I change the existing comments as well or just the new ones?

2023-08-14 03:46 UTC, pupnewfster requested changes, later dismissed

2023-08-14 03:46 UTC, pupnewfster commented on patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch
> ++            p_140384_.currentlyLoading = levelchunk; // Neo - bypass the future chain when getChunk is called, this prevents deadlocks.
`// Neo: bypass...` not `// Neo - bypass...`

2023-08-14 03:48 UTC, Shadows-of-Fire commented
> Do I change the existing comments as well or just the new ones?

I would say update all of them as they are touched in a patch, so yes, all in-line comments to the `// Neo: ` format

2023-08-15 21:03 UTC, marchermans approved these changes
As far as I can tell this indeed fixes it, but testing this was not trivial, I got the deadlock once on the old code, by indeed using the event.

But not again afterwards.

I will merge this now, but yeah we will need to see if it completely fixes the deadlock. Stuff like this is tricky.

2023-08-15 21:03 UTC, merged